### PR TITLE
Update Class Library template for beta7. Closes #313

### LINKED ISSUE #313: ASP.NET Class template for Beta7
Feed used: https://www.myget.org/F/aspnetliterelease/api/v2 
 Sample is here: https://onedrive.live.com/redir?resid=43459A6389A804D9%21102054

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR updates Class Library template for beta7

It restores and builds:
```bash
dnu restore -f https://nuget.org/api/v2/
Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12256

Restoring packages for /Users/piotrblazejewicz/development/ClassLibrary/project.json
  CACHE https://www.myget.org/F/aspnetbeta7/api/v2/
  CACHE https://nuget.org/api/v2/
  GET https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='Microsoft.CSharp'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='Microsoft.CSharp'
  GET https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Collections'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Linq'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Runtime'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Threading'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  OK https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='Microsoft.CSharp' 1194ms
  OK https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Collections' 1256ms
  OK https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Linq' 1486ms
  OK https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Runtime' 1658ms
  OK https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Threading' 1811ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Threading' 1853ms
Writing lock file /Users/piotrblazejewicz/development/ClassLibrary/project.lock.json
Restore complete, 2367ms elapsed

NuGet Config files used:
    /Users/piotrblazejewicz/.config/NuGet/NuGet.Config
    /Users/piotrblazejewicz/development/ClassLibrary/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetbeta7/api/v2/
    https://nuget.org/api/v2/
```
```
dnu build
Build succeeded.
    5 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.0435380
Total build time elapsed: 00:00:01.0812781
Total projects built: 1
```

It shows build warnings due to beta packages version mismatch though:
```bash
/Users/piotrblazejewicz/development/ClassLibrary/project.json(13,29): warning: Dependency specified was Microsoft.CSharp >= 4.0.1-beta-23217 but ended up with Microsoft.CSharp 4.0.1-beta-23225.
/Users/piotrblazejewicz/development/ClassLibrary/project.json(14,31): warning: Dependency specified was System.Collections >= 4.0.11-beta-23217 but ended up with System.Collections 4.0.11-beta-23225.
/Users/piotrblazejewicz/development/ClassLibrary/project.json(15,24): warning: Dependency specified was System.Linq >= 4.0.1-beta-23217 but ended up with System.Linq 4.0.1-beta-23225.
/Users/piotrblazejewicz/development/ClassLibrary/project.json(16,27): warning: Dependency specified was System.Runtime >= 4.0.21-beta-23217 but ended up with System.Runtime 4.0.21-beta-23225.
/Users/piotrblazejewicz/development/ClassLibrary/project.json(17,29): warning: Dependency specified was System.Threading >= 4.0.11-beta-23217 but ended up with System.Threading 4.0.11-beta-23225.
```

Thanks!

/cc
@sayedihashimi @rustd

### CODE REVIEW

**Comment by sayedihashimi** [comment]
I will take a look tomorrow.

**Comment by peterblazejewicz** [comment]
If I write packages that way:
```
"dependencies": {
  "Microsoft.CSharp": "4.0.1-*",
  "System.Collections": "4.0.11-*",
  "System.Linq": "4.0.1-*",
  "System.Runtime": "4.0.21-*",
  "System.Threading": "4.0.11-*"
}
```
there are warning. Tested with *take2* feed.

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks, merged it

**Comment by rustd** [comment]
The final package version will be locked closer to the release so you can check and update the versions before releasing it.

**Pull request merged**
