### PR TITLE
Updated unit test project

### PR DESCRIPTION
**Pull request by suhasj**
@sayedihashimi added unit test project to the main menu

### CODE REVIEW

**Comment by suhasj** [comment]
@sayedihashimi removing the binaries were in the first commit. I have updated the contributors as well

**Comment by sayedihashimi** [comment]
@suhasj sorry I read the changes wrong. When I run through the process the project gets created. When I invoke ```kpm restore``` I get the following error stating that the XUnit.KRunner package cannot be found.

```
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ source kvm.sh
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ kpm restore
Restoring packages for /Users/sayedhashimi/temp/yotest/UnitTest/project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Xunit.KRunner'
Resolving complete, 87ms elapsed
Unable to locate Xunit.KRunner >= 1.0.0-beta1
Restore complete, 89ms elapsed
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ kpm build
```

Is the package in ```nuget.org```? If not do we need to drop a ```nuget.config``` file as well?

**Comment by suhasj** [comment]
I am not sure why `Xunit.Runner` is being pulled. That is the change in PR to rename it to `xunit.runner.kre`. Can you check the project.json of the project ?

**Comment by sayedihashimi** [comment]
OK I think i see what's happening. Since we are using ```.remote()``` it is pulling what's in github. I'll just commit it and then retry.

**Comment by sayedihashimi** [comment]
@suhasj same result with ```xunit.runner.kre```. See below.

```
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ source kvm.sh
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ kpm restore
Restoring packages for /Users/sayedhashimi/temp/yotest/UnitTest/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='xunit.runner.kre'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='xunit.runner.kre' 430ms
Resolving complete, 632ms elapsed
Unable to locate xunit.runner.kre >= 1.0.0-beta1
Restore complete, 635ms elapsed
Sayeds-MacBook-Pro:UnitTest sayedhashimi$ kpm build
```

I just searched nuget.org and it looks like it is not there http://www.nuget.org/packages?q=xunit.runner.kre.

**Comment by suhasj** [comment]
Ah I had some stale packages and that is why it worked on my machine. Apparently this is not pushed yet on nuget yet :(

I can help you revert the changes. This change is not relevant as of now

**Pull request merged**
