### PR TITLE
Made Nancy project template netcoreapp1.0 compatible

### LINKED ISSUE #775: Update Nancy Template after RTM
The Nancy template project are behind the other projects.
It should be at least updated for RTM

/cc @jchannon

### PR DESCRIPTION
**Pull request by jchannon**
Fixes #775.

Summary of the changes in this PR:
 - Updates Nancy project template to use netcore Nancy version for netcoreapp1.0

Thanks!

/cc
@OmniSharp/generator-aspnet-team-push

@peterblazejewicz

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
The main copying routine does not contain rule for added `Program.cs`:
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L277
Same for the core tests.
The scaffolded example won't run because of this:
```
error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```
Thanks!

**Comment by jchannon** [comment]
Will get on it. Couldn't remember how to test locally

**Comment by peterblazejewicz** [comment]
> Couldn't remember how to test locally
- add `Program.cs` to expected files array in Nancy test block
```
npm test
```
- test should fail
- add copy routine to `app/index.js`
- test should pass

**Comment by jchannon** [comment]
Updated, however 29 of the tests fail around subgenerators FYI
screen shot 2016-07-20 at 23 23 07

**Comment by jchannon** [comment]
Not sure why CI is failing, any pointers gratefully received :)

**Comment by peterblazejewicz** [comment]
> Not sure why CI is failing, any pointers gratefully received :)

The Nancy project was the only one without Program.cs. Was, now it has one after RTM update, so the tests are failing:
https://github.com/OmniSharp/generator-aspnet/blob/master/test/subgenerators.js#L32

If you are on hurry remove that use-case and mark it for addition as issue. This will make this PR passsing.
Or rewrite to use Class library project template. It does not have Program.cs by default and has project.json file as expected by use-case.

Thanks!

**Comment by jchannon** [comment]
Removed test

**Comment by peterblazejewicz** [comment]
```
dotnet run
Project NancyApplication (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling NancyApplication for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.5296766
 

Hosting environment: Production
Content root path: /Users/piotrblazejewicz/development/NancyApplication
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```
🚢

**Pull request merged**
