### PR TITLE
Adding real namespaces

### PR DESCRIPTION
**Pull request by david-driscoll**
This adds a utility method that will compute the namespace for a given project.json file.

Rules:
1) Namespace will use the folder name, of the folder project.json is contained in.
2) If the Namespace ends in `.Abstractions`, the last part will be removed,

This also supports nested folders, so if your cwd is something like `<project/ViewModels/Account` the resulting namespace would be `Project.ViewModels.Account`.

Also for new Controllers / Views, if you are in the root of your project, the controllers will default to `Controllers/<Controller>.cs` and the views `Views/<View>.cs`.
  * I'm not certain if there are other conventions to be supported or not. (or I guess if we should support them at all)

### CODE REVIEW

**Comment by sayedihashimi** [comment]
+1 I've been wanting this.

**Comment by david-driscoll** [comment]
Added some tests to validate the convention based behavior.

**Comment by peterblazejewicz** [comment]
> Rules:
> 1) If project.json contains a property namespace that value is used.

The `project.json` has official schema and it does not include `name` or `namespace` property:

http://json.schemastore.org/project

That was something that I hit when trying to provide project-based solution for namespaces. On the second though I've been trying to use `.yo-rc` - which is Yeoman built-in solution for namespacing and project-like scaffolding - but it does not fit usage scenarios for this generator (the location of `.yo-rc` mandates where root of I/O operations is).

I do really want that we provide 'project like' soltuiion for users. I'll able to review PR locally later today (CEST time)

**Comment by david-driscoll** [comment]
I figured that point would come up. :smile:  I realize that it isn't officially used by dnx or anything, but it is just JSON, so the property if unused should just be ignored.  We could consider renaming it to something like `generator-namespace` to make it appear less as an officially supported property.

Originally I had lifted `Storage` from yeoman and had created a `.aspnet-rc.json` file that would live in the root (next to, presumably `global.json`) and manage the namespaces settings for each project.  This solution was working, but I wasn't sure if we wanted to stay away from using a config file approach or not, which is why I had a "drive home epiphany" and went with the `project.json` approach for now.

**Comment by david-driscoll** [comment]
I also had a workaround for `.yo-rc.json` by simply capturing the `cwd` before we call generator super class, and the using that `cwd` in processing later.

**Comment by sayedihashimi** [comment]
Oh yeah this, I talked to @billhie and @davidfowl about this. Ideally we can come up with a solution that works for`yo aspnet` and `visual studio`.

I think we have two high level options.

 1. Add a new element in `project.json` where we store all these settings. Perhaps we call it `tooling` or `toolingsettings`.
 1. Add a new file where we keep all these settings. If we do this I'd like to hide the file under `Properties`

I talked to @davidfowl and he had some hesitations about putting the settings in `project.json`, but at one point it seemed he was OK with it. I'm not sure where he stands on it now.

I'd like to avoid adding yet another config file, but I'd also like to ensure that we don't pollute the `project.json` with too many values.

@davidfowl what's your latest thoughts on `yo aspnet`/`visual studio` writing the default namespace in a `tooling` section in `project.json`? This value will be read when files are added to existing projects.

**Comment by david-driscoll** [comment]
For today, we could remove the dependence on project.json, and simply just default to the folder name.  Then once the "offical way" solidifies, it could be added in.

**Comment by peterblazejewicz** [comment]
@david-driscoll 
I have realised that schema validator https://github.com/OmniSharp/atom-json-schema is relaxed for keys/properties not defined by schema
+1
Should we start issue on aspnet/home that `there is no easy way to programmatically figure out project name` in ASP.NET 5? The VS solution has an obvious name and contains project reference.

**Comment by david-driscoll** [comment]
maybe @sayedihashimi could say if we should open a new on home.

For now (so we can move forward with the PR) do these new rules make sense (dropping the extra property in `project.json`):

1) Project name is assumed based it's folder name
  1a) If the folder is in the form of `Project.Abstractions` the name will be shortened to be just `Project`

**Comment by peterblazejewicz** [comment]
@david-driscoll 


> For now (so we can move forward with the PR) do these new rules make sense (dropping the extra property in project.json):

Yes, for me :+1:

**Comment by david-driscoll** [comment]
Alright change has been made, for now the namespace will just be inferred based on the project.json folder, as well as the `process.cwd()`.

**Comment by peterblazejewicz** [comment]
> Alright change has been made, for now the namespace will just be inferred based on the project.json folder, as well as the process.cwd().

It works for me. The Yo has similar implementation:
https://github.com/yeoman/generator/blob/f76cbe8312d57fffe7dbe8267ce0c975fb42f29b/lib/base.js#L757-L769

I think that NuGet package namespace (`id`) is also created by root folder name when using `dnu pack`.

**Comment by peterblazejewicz** [comment]
@david-driscoll 
It will have to wait a little to let everyone try and look around. I'll also have to check some corner cases.
Is this OK?

**Comment by david-driscoll** [comment]
No rush, I just didn't want the PR to sit around waiting for a response about where to put a property in `project.json`.

I do have a couple presentations coming up in October, and it would be great to have this and #367 in by then because it makes the template experience in atom so much nicer from a usage perspective as well as a demo perspective.  That said, worse case scenario I can always fake it if I have to. :+1:

**Comment by sayedihashimi** [comment]
I think we should at least make a new section in `project.json` that makes it clear that the values are used by tools and not the runtime. Having `namespace` as a top level element like that makes it look like the runtime may consume that value.

How about

```json
 "tooling":{
      "defaultnamespace":"MyCoolApp"
 }
```

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I've created a topic on aspnet/home:
https://github.com/aspnet/Home/issues/946
The David's implementation follows steps used in other existing code and adding a key to `project.json` could only help us (and others). The *name* key is obvious pattern used elsewhere, the same *namespace*. I'm not sure about other names (and we should not talk about names - the programmers nightmares :D )

**Comment by sayedihashimi** [comment]
It doesn't look like anyone is responding on https://github.com/aspnet/Home/issues/946. I don't think we should wait on them. I think we should just add the following to project.json.

```
 "tooling":{
      "defaultnamespace":"MyCoolApp"
 }
```

@david-driscoll @peterblazejewicz thoughts?

I think we should aim to merge this in the next few days so that we can be in good shape for beta8.

**Comment by peterblazejewicz** [comment]
:+1:

**Comment by david-driscoll** [comment]
sounds fine to me :smile:

**Comment by nosami** [comment]
Capital 'N' in `defaultNamespace` maybe?

**Comment by david-driscoll** [comment]
PR Updated, @nosami fix is a quick find and replace if needed.

**Comment by peterblazejewicz** [comment]
> Capital 'N' in defaultNamespace maybe?

the schema uses camelCase everywhere, so :+1: . But it could be refactored later as mentioned.

**Comment by david-driscoll** [comment]
anyone else have a preference?  I can make the change quickly (I honestly have no preference in this case)

**Comment by Spinarooni** [comment]
+1 for camel case.

**Comment by sayedihashimi** [comment]
Since other elements are using camel case +1 to that.

**Comment by david-driscoll** [comment]
Updated.

**Comment by peterblazejewicz** [comment]
@david-driscoll 
Just small remark:
I understand that namespace should be used also in config files or client-side modules application namespace? For example in place of 'app' in Angular templates:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/AngularController.js#L5
or as name in Bower config:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/bower.json#L2
or NPM module:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/package.json#L3
I'll test on Windows 8.1 tomorrow (fingers crossed)

**Comment by sayedihashimi** [comment]
I tried it out, it seems to work well. The only issue I noticed is what @peterblazejewicz mentioned above, and it looks like the [build is failing](https://travis-ci.org/OmniSharp/generator-aspnet/builds/83339622).

**Comment by david-driscoll** [comment]
I have no idea how the build would be broken, it was working locally for me.  We'll see with this build.

**Comment by david-driscoll** [comment]
@peterblazejewicz @sayedihashimi build passed, I added namespace to package.json, bower.json and the angular templates.

**Comment by peterblazejewicz** [comment]
@sayedihashimi @david-driscoll 
I've no chance yet to test on Windows OS, only *nix based cli. Does it bother you?

**Comment by sayedihashimi** [comment]
Ok I think we can merge this. We will hear if there are any issues w windows.

@peterblazejewicz any concerns w merging?

**Comment by david-driscoll** [comment]
I'm on Windows so it's working for me arm

On Mon, Oct 5, 2015 at 5:12 PM Sayed Ibrahim Hashimi <
notifications@github.com> wrote:

> Ok I think we can merge this. We will hear if there are any issues w
> windows.
>
> @peterblazejewicz <https://github.com/peterblazejewicz> any concerns w
> merging?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/generator-aspnet/pull/366#issuecomment-145669692>
> .
>
-- 
Thanks,
David

**Comment by peterblazejewicz** [comment]
@david-driscoll  @sayedihashimi 
Sorry, had a hard day at work. 
:ship: 
We will refactor if required later and watch for reports carefully.

**Comment by peterblazejewicz** [comment]
@spboyer 
Shayne, as Sayed could be `overbooked` elsewhere, can you also review this PR?
If it's OK let's merge it
Thanks!

**Comment by spboyer** [comment]
@peterblazejewicz @david-driscoll  let me pull down the branch and build/test

**Comment by spboyer** [comment]
I would like to see some tests added for the namespace, checking at least one of the files for the content to be sure that it is adding the namespace being asked for/default.

@david-driscoll

**Comment by spboyer** [comment]
I just pulled the branch from @david-driscoll and generated the WebSimple and there is `namespace` in package.json or project.json and using the subgenerator `yo aspnet:MvController AboutController` still yields `MyNamespace`

**Comment by spboyer** [comment]
This is a great addition! Thanks for the feedback.  @david-driscoll can you add test coverage as mentioned in my previous comment?

**Comment by david-driscoll** [comment]
Absolutely, now that I understand how to test for file contents properly (I must have missed it).

I couldn't replicate the `MyNamespace` though, `yo aspnet:MvcController AboutController` is working for me from a `websimple` project.

**Comment by spboyer** [comment]
@david-driscoll i made mistake on my previous comment, when i pulled your repo i forgot to switch to the `namespace` branch prior to running.  That's why i like test coverage and I test 2x :smile:

**Comment by david-driscoll** [comment]
haha, fair enough. :+1:

**Pull request merged**
