### PR TITLE
Added namespace normalization code

### PR DESCRIPTION
**Pull request by sandcastle**
Added namespace normalization logic to address #256.

This change takes a dependency on the `vs_projectname` package.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@sandcastle Terrific :clap: 

/cc @sayedihashimi @spboyer 
> This change takes a dependency on the vs_projectname package.

What is your opinion on adding this as dependency? Is this OK? What do you think about @sandcastle module?

**Comment by peterblazejewicz** [comment]
/cc @sayedihashimi @spboyer

> This change takes a dependency on the vs_projectname package.

What is your opinion on adding this as dependency? Is this OK? What do you think about @sandcastle module?
As the Glenn's module will become crucial point in detail implementation, the topic should be at least discussed. In my previous job and at other organization we fork crucial module - e.g. to keep it under organization umbrella, commit fixes back to original module repo, to have a fallback direct git reference in NPM package, etc. The Glenn's module has a nice, little feature and module serves single purpose only.

Thanks!

**Comment by sayedihashimi** [comment]
Seem fine to me. It looks like the package was created specifically for this. I checked the license and it's using the [MIT License](http://opensource.org/licenses/MIT) which I think is OK. I will merge it.

**Comment by spboyer** [comment]
LTGM - vs_projectname is a good package, should add some test(s) perhaps?  Can we close #256?
@sayedihashimi @peterblazejewicz

**Pull request merged**
