### PR TITLE
CTP 6 templates

### PR DESCRIPTION
**Pull request by spboyer**
Project structure for templates is changing from `/samples` to `/templates/projects`

CTP 6 templates have been added for 
* web
* webapi
* empty

Removed existing 
* empty
* web

from samples folder.
New templates also support `namespace` as `applicationname` just as Visual Studio templates. 

Notes
* EF 7 support for xplat not complete, files included, implementation commented out.
* `if mono` and commented **Register** link from `_Layout.cshtml` 
* All DB files and Migration files are included for Windows platform
* `"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta3"` commented in project.json for non Visual Studio IDE

@shanselman @sayedihashimi @rustd

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@spboyer BrowserLink nuget package is now on nuget.org. Can you add it back to project.json and startup.cs and see what happens when you run it on OSX? If we get a runtime error let's comment out the line in startup.cs but leave the package in project.json if it doesn't cause issues.

**Comment by spboyer** [comment]
@sayedihashimi :+1:  good to go.  I will make the edit and add to this PR

**Comment by peterblazejewicz** [comment]
I must say I'm impressed - I can run this build on my OS X (not all yet, but at least WebApplication):

:clap:

**Comment by spboyer** [comment]
@sayedihashimi @peterblazejewicz fixed issues with webapi and empty templates.  Missing wwwroot folder now running and restoring.

Need to `kpm restore`, `kpm build`, `k kestrel`  

Added `app.UseStaticFiles()` and `app.UseWelcomePage()` to empty template.  Makes it nice and runs "something" out of the gate.

**Comment by peterblazejewicz** [comment]
@spboyer WebAPI now works (restore/build/run):

**Comment by sayedihashimi** [comment]
+1 fantastic, I'll take a look later today

**Comment by sayedihashimi** [comment]
OK I have reviewed the project generators worked under ```beta3``` kvm with the exception of the the Nancy template and the Unit test template. 

I have opened the following issues #74 and #75 to track getting those updated for beta 3. 

I'd like to go ahead and release what we have and then work with appropriate folks to get those two templates updated.

@spboyer do you want to merge and publish? Publish instructions on the [wiki](https://github.com/OmniSharp/generator-aspnet/wiki/How-to-Publish-Changes)

**Pull request merged**
