### PR TITLE
Update dnx console command in index.js

### PR DESCRIPTION
**Pull request by PaitoAnderson**

### CODE REVIEW

**Comment by sayedihashimi** [comment]
+1

**Comment by peterblazejewicz** [comment]
whoa, there is finally official doc that `run` just works:
> The dnx command is used to execute a managed entry point (a Program.Main function) in an assembly. By default, the **dnx run** command looks in the current directory for the project to run. To specify a different directory, use the –project switch.
https://docs.asp.net/en/latest/dnx/console.html?highlight=console

:ship:

**Comment by peterblazejewicz** [comment]
@PaitoAnderson 
Everything is OK, but you've based on wrong branch. `rc1` branch was feature branch. Please resubmit from `master`.
Thanks!

**Comment by PaitoAnderson** [comment]
Thanks @peterblazejewicz. Will do.

**Pull request merged**
