### PR TITLE
:lock: Do not use relative URLs for CDNs

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit fixes regression change compared to aspnet/Templates
in RC1 updates - where relative CNDs URLs have been committed with
changes.
This commit introduces HTTPS based URLs as explained in H5PB:
http://git.io/vBfqJ

Thanks!

### CODE REVIEW

**Comment by spboyer** [comment]
saw this last night.

**Comment by sayedihashimi** [comment]
Do you know this has been reported on the templates repo?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
No, that was in mine commit.Tempaltes are OK, I've checked that in aspnet/Templates source when pushing this one.

**Comment by sayedihashimi** [comment]
Ok thanks

**Pull request merged**
