### PR TITLE
Add user secrets ID to project.json.  Addresses Issue #303

### PR DESCRIPTION
**Pull request by Spinarooni**
Adds the ID to:

* Web Basic
* Empty Web
* Web API

Thoughts?

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
We are diverging from original templates, so we have to ask MS folks:
@sayedihashimi 
We have now aspnet/templates, so we could brought topics there and reintroduce here once given OK

**Comment by peterblazejewicz** [comment]
@Spinarooni 
Randy, we have got a green light to be little ahead of sacred VS templates. Can you update and rebase your PR? The beta8 is out and it would not merge clean. It'd be nice to have a single commit, but that's not required.
Thanks!

**Comment by Spinarooni** [comment]
@peterblazejewicz  PR updated.

**Comment by peterblazejewicz** [comment]
Q: should we add 'Microsoft.Framework.Configuration.UserSecrets' to `package.json`? 
Just to discuss this topic. The secret manager tool will work with `project.json` just after we add that storage key. The package in `project.json` is only required if source code is to call e.g. `AddUserSecrets'.

**Comment by Spinarooni** [comment]
I was basing the changes off the Web template and it's added there as a dependency.  If it's not needed to use the tool then I do not see why it would need to be a dependency.  After looking further the webbasic, webapi, and empty templates don't call `AddUserSecrets` so it probably is not needed.

**Comment by peterblazejewicz** [comment]
@spboyer ?

**Comment by spboyer** [comment]
This is not a needed PR. You can use the the CLI or "Global Tool" to install, set, remove etc saw defined here - https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration

**Comment by peterblazejewicz** [comment]
The CLI tool lookups for `userSecretsId` key in `project.json`:
> The tool will then lookup the value of the <SuperSecretStuffId> using the value of userSecretsId in your project.json.

this is why PR generates the keys.

**Comment by spboyer** [comment]
Commands:
  set     Sets the user secret to the specified value

The functionality is only needed if the application is taking advantage of oAuth. If anything we should add a question or option. This is why the webapp has it and the others do not. If the simple template has it, it should be removed.

**Comment by peterblazejewicz** [comment]
> The functionality is only needed if the application is taking advantage of oAuth.

This is too extreme argument I think. We use MVC5/WebForms/Services at work and we use ton of configuration files - no one of them provides the same experience as new UserSecrets tool and api.

As example, the secrets can be used in WebAPI as well:
http://shellmonger.com/2015/08/09/asp-net-and-the-secret-store/
https://github.com/adrianhall/blog-code/tree/blog-08092015-2/UserSecretWeb

**Comment by peterblazejewicz** [comment]
a note: I think there should be a test for content in `project.json` - to be sure that we do not remove that keys when updating content in future - the aspnet/templates supports only web app project with generated keys.

**Comment by Spinarooni** [comment]
@peterblazejewicz I'll look to add the tests.

**Comment by Spinarooni** [comment]
@peterblazejewicz Tests added.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Your thoughts on this if you don't mind?

**Comment by peterblazejewicz** [comment]
@Spinarooni 
I've made different PR which I think addresses our expectations from #303 in more general and opaque way: #548 
It does not require us to modify aspnet/Templates with another custom sections, instead it should work with any existing `project.json` in ASP.NET5 projects.
Mind checking?

I think objections expressed here and other threads are the basis why this specific PR has not yet landed.

Thanks!

**Comment by Spinarooni** [comment]
#548 seems good to me.  I'll close this one.

**Comment by peterblazejewicz** [comment]
@Spinarooni Thanks!

**Pull request closed without merging**
