### PR TITLE
[ON HOLD] Added back a Unit Test template project with xUnit / xUnit.Runner.AspNet

### PR DESCRIPTION
**Pull request by larsw**
xunit* points at: 2.0.0-rc3-* version (sample project builds & test runner runs ok).

### CODE REVIEW

**Comment by larsw** [comment]
Now what? tests passed before I pushed the changeset. *scratch head*

**Comment by sayedihashimi** [comment]
@larsw I looked at the changes and merged them with some other changes that came in after the PR. I've created a new branch with all the changes at https://github.com/OmniSharp/generator-aspnet/tree/larsw-unittest-beta3.

When I run the unitest generator on OSX I get an error. Have you tested on OSX or Linux?

**Comment by larsw** [comment]
Only tested on Windows.

**Comment by larsw** [comment]
I'll test it tonight

**Comment by larsw** [comment]
Experiencing the same thing. https://github.com/aspnet/Testing/issues/60 seems to be related. I' guessing that on of the xUnit nuget packages (or their dependencies) specifies System.XML and not System.Xml as a dependency. This will work on Windows, but not Linux/Mac OS X as of now :-/

**Comment by peterblazejewicz** [comment]
The same thing here:
https://gist.github.com/peterblazejewicz/346a859a8c2662bba130
This https://github.com/aspnet/Testing/issues/60 is a blocker for UnitTest release, I think we should remove it until fixed in core - so we won't mislead people (including removing commented code).

**Comment by sayedihashimi** [comment]
I submitted a PR to fix this in xunit that was recently merged https://github.com/xunit/xunit/pull/339

**Comment by spboyer** [comment]
@sayedihashimi are we good with this one?

**Comment by sayedihashimi** [comment]
@spboyer the xunit update doesn't look like it's on nuget.org yet.

FYI it looks like the nuget package name changed as well. I've updated the PR to fix for the changes into a new branch at ```unittest```. Can we maintain that in this new branch.

@bradwilson do you know when updated nuget packages for xunit will make it to nuget.org?

**Comment by bradwilson** [comment]
ASP.NET has been removed from 2.0 RC 4 as we prepare for RTM (since we cannot take prerelease package references from non-prerelease packages; this is a limitation of NuGet).

It will return in 2.1 Beta 1, which we will release shortly after 2.0 RTM.

In the meantime, you can continue to use RC 3.

**Comment by spboyer** [comment]
@sayedihashimi good on this?

**Comment by sayedihashimi** [comment]
I think we can get it updated on a week or so.

**Comment by spboyer** [comment]
@sayedihashimi @bradwilson Can we revisit? Or should this be closed and move to generator-aspnet-xunit?

**Comment by bradwilson** [comment]
FYI the runner is getting renamed in the next beta release to xunit.runner.dnx to reflect the wider support for all DNX project types (not just ASP.NET).

**Pull request closed without merging**
