### PR TITLE
Incorporate RC1 changes into gulpfile.js

### PR DESCRIPTION
**Pull request by scottaddie**
Updated the "web" and "webbasic" projects' gulpfile.js to match that of the StarterWeb template in the RC1 release of the Templates repo. See that gulpfile.js [here](https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/gulpfile.js).

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@scottaddie https://github.com/scottaddie/generator-aspnet/blob/gulp_rc1_updates/templates/projects/web/gulpfile.js has 48 lines and https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/gulpfile.js has 46 lines. What's the difference between the files?

**Comment by peterblazejewicz** [comment]
> What's the difference between the files?

https://www.diffchecker.com/rboshuo3

**Comment by scottaddie** [comment]
The difference is that the "min:js" task's `gulp.src` options.base parameter spans 3 lines in this repo. That's how it was when I submitted the PR, so I assumed it was done that way for a reason and left it alone. Would you prefer to have it all on a single line?

**Comment by peterblazejewicz** [comment]
White space and formatting is always a side problem. E.g. https://github.com/aspnet/Templates/issues/226
LGTM. Tested OS X
:ship:

**Comment by peterblazejewicz** [comment]
this is diff without white-space:
https://github.com/OmniSharp/generator-aspnet/pull/505/files?diff=split&w=1

**Pull request merged**
