### PR TITLE
Update Semantic UI dependency to 2.2.2

### PR DESCRIPTION
**Pull request by jackjwilliams**
Fixes #bugnumber.

Summary of the changes in this PR:
 - Update overrides/semantic/web/bower.json to Semantic version 2.2.2
 - Update overrides/semantic/webbasic/bower.json to Semantic version 2.2.2
 - ...

Thanks!

/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I'll close and reopen to kick Travis again

**Comment by jackjwilliams** [comment]
Ok - it keeps saying "This branch has conflicts that must be resolved", but it was a straight fork, update, push so I'm not sure why.

**Comment by peterblazejewicz** [comment]
I've checked your PR. It started from very old master state, hence merge conflicts. Your PR started as commit on master instead of using topic branch. So now it is not possible to easily fix this.
Just copy this commit over to new branch, update your master and then rebase topic branch fixing conflicts in both bower.json. I've to make this via new commits in branch, but commits can be squashed into single commit later.

**Comment by jackjwilliams** [comment]
Hrmmm I'm no github pro, how do I reset my fork off of OmniSharp/generator-aspnet? Now my forked master has the changes

**Comment by peterblazejewicz** [comment]
http://stackoverflow.com/questions/1628563/move-the-most-recent-commits-to-a-new-branch-with-git
(move your last commit from master into new branch - as in SO topic, then update master from Omnisharp/master and then rebase topic branch with master)

**Comment by peterblazejewicz** [comment]
closed with https://github.com/OmniSharp/generator-aspnet/pull/792

**Pull request closed without merging**
