### PR TITLE
Fixes white space in our code as per configs

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit applies white space settings to our own
source code files and covers JavaScript and related
type of source code file

The config files for source code have been just added:
https://github.com/OmniSharp/generator-aspnet/pull/121
and this PR applies changes to source-code as per config.

Tested with `npm test` and `/e2etest.sh` locally.

Thanks!

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I can see only one side-off change that can be removed if requested via rebase:
https://github.com/OmniSharp/generator-aspnet/pull/129/files?w=1
https://github.com/OmniSharp/generator-aspnet/pull/129/files?diff=unified&w=1
Thanks!

**Comment by sayedihashimi** [comment]
Should we add a .gitconfig file with carriage return/whitespace settings? More info at http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I think that's not related. We have different white-space characters in source codes: spaces vs. tabs, 2 char per space vs. 4 char per space.
Using different white-space characters do matters when using source control (or Markdown/Jade/etc).
We do not have `.gitattributes` config file from original `generator-generator` though, and it could manage LF/CRLF normalization on committing:
https://github.com/yeoman/generator-generator/blob/master/app/templates/gitattributes
https://help.github.com/articles/dealing-with-line-endings/

**Comment by sayedihashimi** [comment]
Ok thanks for the input.

**Comment by spboyer** [comment]
@peterblazejewicz can you fix the merge issues

**Comment by peterblazejewicz** [comment]
@spboyer Let's scratch this PR. During rebase I've come to conclusion that involved files `app/index.js` and `test/test-core.js` are just to important to manually correct this. Let me close this and just resubmit. 
Sounds OK?
(I know you guys are busy)

**Comment by spboyer** [comment]
Sounds good

**Comment by peterblazejewicz** [comment]
:closed_book:

**Pull request closed without merging**
