### PR TITLE
Update Empty web application template for beta5

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit update template files for Empty web application:
- new hosting.ini file added to project
- the test for Empty web application is updated to check for hosting.ini
- project file updated to beta5 structure
- the readme.md is fully updated and based on VS generated readme html

This PR passes `npm test`, creates a project which OmniSharp in Atom compiles and `locks`. I've a problem with restoring it (as other projects) as I have to reconfigure my machine though.
The PR should be ready to test againts local installation of beta5.

Thanks!

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@peterblazejewicz when running ```dnx . kestrel``` I get the following error

```
Sayeds-MacBook-Pro:EmptyApplication sayedhashimi$ dnx . kestrel
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IApplicationEnvironment] (IServiceProvider provider) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

Are you getting the same error?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I've different problems:
`dnu build` fails with 15 errors:
https://gist.github.com/peterblazejewicz/c111e5243a76cf560c4e
`dnx . kestrel` fails with different error:
https://gist.github.com/peterblazejewicz/145f95496fd8162cf422
I've updated dnvm to beta5:
```
dnvm
    ___  _  ___   ____  ___
   / _ \/ |/ / | / /  |/  /
  / // /    /| |/ / /|_/ / 
 /____/_/|_/ |___/_/  /_/  

.NET Version Manager - Version 1.0.0-beta5-10378
By Microsoft Open Technologies, Inc.

DNVM can be used to download versions of the .NET Execution Environment and manage which version you are using.
You can control the URL of the stable and unstable channel by setting the DNX_FEED and DNX_UNSTABLE_FEED variables.

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
```

**Comment by danroth27** [comment]
Please try out the candidate beta5 packages from https://www.myget.org/f/aspnetbeta5/api/v2.

For the Kestrel issue, why is WebListener showing up in the stack? Is your kestrel command setup correctly?

**Comment by sayedihashimi** [comment]
I chatted with @danroth27 and @rustd they will investigate and get back to us. There is an issue with how kestrel is configured.

**Comment by peterblazejewicz** [comment]
The PR is update according to @rustd input (package, hosting, etc), rebased and squashed. The local tests are updated and pass:
```
aspnet - Empty Application
    Checking directories
      ✓ Application directory created
      ✓ wwwroot directory created
    Checking files
      ✓ emptyTest/hosting.ini created.
      ✓ emptyTest/project.json created.
      ✓ emptyTest/Startup.cs created.
      ✓ emptyTest/wwwroot/README.md created.
```

The restore passes:
https://gist.github.com/peterblazejewicz/0eeea6995ca98cc64253
While build and kestrel fail:
https://gist.github.com/peterblazejewicz/443160032dc4f4e941aa
https://gist.github.com/peterblazejewicz/642e7aded8eda68c2b64

**Comment by danroth27** [comment]
@BrennanConroy @glennc

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz I've merged it.

I was able to build and run w/o errors. If you are still having errors try the following:
 - delete packages folder in ```~/.dnx/packages```
 - set dnvm to beta5
 - restore packages with ```dnu restore -f https://nuget.org/api/v2```
 - build and run

Note: I am still unable to stop kestrel on Mac such that the port is released. The only way I found to close kestrel is with ```CTRL+Z``` and that keeps the port in use. See my previous comment https://github.com/OmniSharp/generator-aspnet/issues/191#issuecomment-113790859

**Comment by BrennanConroy** [comment]
```CTRL+Z``` will move the process to the background so it will continue to exist. @halter73 is working on Kestrel and knows about kestrel not exiting.

**Comment by sayedihashimi** [comment]
So it will be fixed for beta5?

**Comment by sayedihashimi** [comment]
Also is there an issue tracking this?

**Pull request merged**
