### PR TITLE
Add DockerFile to templates and subgenerator

### LINKED ISSUE #364: Can we add `Dockerfile` subgenerator?
I've been using aspnet/aspnet-docker based images to host generator-aspnet web appplications.
If we start adding a Dockerfile template subgenerator the users could get at some point in the future the same features that are coming to VS (dockerizing ASP.NET 5 applications):
http://docs.asp.net/en/latest/publishing/docker.html
http://www.hanselman.com/blog/PublishingAnASPNET5AppToDockerOnLinuxWithVisualStudio.aspx

Using official MS Docker image for ASP.NET 5:
https://hub.docker.com/r/microsoft/aspnet/
user could (assuming she has Docker installed) run application in container:
```
docker build -t my-app .
...
Successfully built 0be1d149ce39
```
```
docker run -i -t -p 5000:5000 my-app
Application started. Press Ctrl+C to shut down.
```
image

The required changes:
```patch
diff --git a/Dockerfile/USAGE b/Dockerfile/USAGE
new file mode 100644
index 0000000..d7c398d
--- /dev/null
+++ b/Dockerfile/USAGE
@@ -0,0 +1,8 @@
+Description:
+	Creates a new Docker configuration file
+
+Example:
+	yo aspnet:Dockerfile
+
+	This will create:
+		Dockerfile
diff --git a/Dockerfile/index.js b/Dockerfile/index.js
new file mode 100644
index 0000000..1ac80fc
--- /dev/null
+++ b/Dockerfile/index.js
@@ -0,0 +1,13 @@
+'use strict';
+var util = require('util');
+var ScriptBase = require('../script-base-basic.js');
+
+var Generator = module.exports = function Generator() {
+  ScriptBase.apply(this, arguments);
+};
+
+util.inherits(Generator, ScriptBase);
+
+Generator.prototype.createItem = function() {
+  this.generateStandardFile('Dockerfile', 'Dockerfile');
+};
diff --git a/templates/Dockerfile b/templates/Dockerfile
new file mode 100644
index 0000000..2028286
--- /dev/null
+++ b/templates/Dockerfile
@@ -0,0 +1,13 @@
+FROM microsoft/aspnet:1.0.0-beta7
+
+COPY project.json /app/
+
+WORKDIR /app
+
+RUN ["dnu", "restore"]
+
+COPY . /app
+
+EXPOSE 5000
+
+ENTRYPOINT ["dnx", "-p", "project.json", "kestrel"]
diff --git a/test/subgenerators.js b/test/subgenerators.js
index 98e22e7..a35576c 100644
--- a/test/subgenerators.js
+++ b/test/subgenerators.js
@@ -48,6 +48,11 @@ describe('Subgenerators without arguments tests', function() {
     util.fileCheck('should create tsconfig.json file', 'tsconfig.json');
   });
 
+  describe('aspnet:Dockerfile', function() {
+    util.goCreate('Dockerfile');
+    util.fileCheck('should create Dockerfile file', 'Dockerfile');
+  });
+
 });
 
 /*
```

### PR DESCRIPTION
**Pull request by spboyer**
Closes #364

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@spboyer 
These 'Dockerfile'(s) are just the same `Dockerfile.txt` template.
I think it would be better to reuse template - just like with `.gitignore` reused in generator - so we keep number of content as low as possible and minimize update time (yada, yada, you know what I mean).

**Comment by spboyer** [comment]
@peterblazejewicz agreed - 1 min

**Comment by peterblazejewicz** [comment]
@spboyer 
It builds OK on my machine (Docker version 1.8.2, build 0a8c2e3). I'll check all templates later tooday.
Mind squashing into single commit now?

@sayedihashimi 
Will you be able to review PR with Docker?

**Comment by sayedihashimi** [comment]
+1 thanks guys

**Comment by peterblazejewicz** [comment]
/cc 
@stuartleeks
https://twitter.com/stuartleeks/status/646678223808524288

**Comment by peterblazejewicz** [comment]
@spboyer 
Also USAGE file:
```diff
diff --git a/Dockerfile/USAGE b/Dockerfile/USAGE
new file mode 100644
index 0000000..d7c398d
--- /dev/null
+++ b/Dockerfile/USAGE
@@ -0,0 +1,8 @@
+Description:
+   Creates a new Docker configuration file
+
+Example:
+   yo aspnet:Dockerfile
+
+   This will create:
+       Dockerfile
```
When ready and merged I'll update main README (I'll create another issue for this)

**Comment by peterblazejewicz** [comment]
Good catches with `Dockerfile` character case :+1:

**Comment by peterblazejewicz** [comment]
OK. I think I've tested all templates with `docker build ..` + `docker run` (stop/rm and others) methods using Docker 1.8 on OS X.

**Comment by spboyer** [comment]
@peterblazejewicz all done with verified on multiple machines with docker machine

**Comment by peterblazejewicz** [comment]
@spboyer 
Mind squasing into single commit?
@sayedihashimi 
we are ready to :ship: this one

**Comment by spboyer** [comment]
I used a couple machines for the commit, having a challenge with the squash, is it really an issue?

**Comment by peterblazejewicz** [comment]
@spboyer 
Nope :)

**Comment by peterblazejewicz** [comment]
@spboyer 
Shayne, you have mentioned a blog post. When you're ready and make it published please ping Sayed
Also if you finish before next standup: http://live.asp.net/ ping Jon Gallowey
Thanks!

**Comment by spboyer** [comment]
Yea working in that, it's a long one. When are we publishing this to npm?

**Comment by peterblazejewicz** [comment]
> When are we publishing this to npm?

@sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks everyone [`0.0.75`](https://www.npmjs.com/package/generator-aspnet) has been released with this

**Pull request merged**
