### PR TITLE
Install Bower to bower_components folder then publish to wwwroot using Gulp

### PR DESCRIPTION
**Pull request by markrendle**
I've made quite a lot of changes to do Bower properly (in WebSimple), and keep `wwwroot` as a build target instead of a source+public directory.

I've only done it for Gulp so far, and I'm opening this PR to check whether people like before I spend the time doing it for the Grunt option too.

So, good or bad?

### CODE REVIEW

**Comment by spboyer** [comment]
I like the direction, I've been using some gulp patterns similar to where this is headed. Check out this repo from @johnpapa for gulp patterns. https://github.com/johnpapa/gulp-patterns

**Comment by markrendle** [comment]
There's some good stuff in there, I'll try to incorporate some of it (e.g. automatically `gulp wiredep` after `bower install`).

**Comment by peterblazejewicz** [comment]
@markrendle 
Are this changes available in VS IDE as well? The project does not rewrite implementation details from VS templates, just expose the same content to users without VS IDE.
So are this changes in sync with current, next version of VS IDE implementation/templates?
To illustrate a problem: for me it just sucks that VS templates are using outdated (by 2 years) Bootstrap version, but I cannot change this, only submit to: https://github.com/aspnet/Tooling/issues
/cc @sayedihashimi

**Comment by nosami** [comment]
So, no innovation allowed here?

**Comment by peterblazejewicz** [comment]
@nosami I didn't mean that. I meant: if we made change here, there will be different content generated via VS and generator.

**Comment by markrendle** [comment]
I don't know what the VS templates look like now. All I know is that this is the
correct way to use Bower + Gulp.
There is nothing at all to stop VS users from using yo to generate projects, if
they want more control over their templates.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.1]
On Thu, Jul 9, 2015 at 22:07, OmniSharp/generator-aspnet
<reply@reply.github.com>
wrote:
@markrendle [https://github.com/markrendle]
Are this changes available in VS IDE as well? The project does not rewrite
implementation details from VS templates, just expose the same content to users
without VS IDE.
So are this changes in sync with current, next version of VS IDE
implementation/templates?
To illustrate a problem: for me it just sucks that VS templates are using
outdated (by 2 years) Bootstrap version, but I cannot change this, only submit
to: https://github.com/aspnet/Tooling/issues
[https://github.com/aspnet/Tooling/issues]
/cc @sayedihashimi [https://github.com/sayedihashimi]

—
Reply to this email directly or view it on GitHub
[https://github.com/OmniSharp/generator-aspnet/pull/268#issuecomment-120144402] .[https://github.com/notifications/beacon/AAK4QpTgw1QooF0_qs34NDEjyPEsNquPks5obtoTgaJpZM4FVSk_.gif]

**Comment by sayedihashimi** [comment]
Thanks for the contribution and the discussion here. Let me clarify things a bit.

Here is how I view the `yo aspnet` project and goals. `yo aspnet` should be the primary method for users to get started with ASP.NET 5 on any platform. When users use `yo aspnet` they can be sure that they are getting high quality templates which _align_ with the templates delivered from Visual Studio.

By _align_ I do not mean that they are exactly the same content. There are situations where the output of `yo aspnet` can be different than what VS produces. We already have a few differences. For example `yo aspnet` uses the EF in memory store for DB because we don't have a persistence story for DB on xplat.

I think we should use `yo aspnet` as an avenue to channel specific feedback on templates to the ASP.NET team. Whenever a contribution comes in that meets the following.
 - Is high quality
 - The community agrees that it's a positive addition

Then we should take the contribution. At that point I'll work with the ASP.NET team to try and get the next version of the VS templates updated. Ideally we can keep the templates in sync for the most part to keep updates simple. If for some reason VS is not able to make the changes then for areas that we diverge we'll have to be aware so that we don't lose those on the next asp.net release when templates are updated.

For this particular PR it sounds like we are hearing good feedback from the community here, and I know that @markrendle is an ASP.NET expert so I'm sure it's also high quality. @markrendle I noticed that the build is failing, could you update the PR to get the tests to pass? I think you just need to delete one or more test cases. Does anyone have any concerns with the PR?

I didn't realize that Visual Studio references a 2 year old bootstrap package. I've brought this up with Scott Hunter and we should certainly get that fixed in the VS templates.

**Comment by peterblazejewicz** [comment]
> I didn't realize that Visual Studio references a 2 year old bootstrap package. I've brought this up with @coolcsh and we should certainly get that fixed in the VS templates.

@sayedihashimi  I think that's OK as I wrote - you guys just should provide a channel for people to complain about this and request update :)

**Comment by markrendle** [comment]
I will get the tests passing and implement the same functionality for Grunt over
the weekend.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.1]
On Fri, Jul 10, 2015 at 18:59, OmniSharp/generator-aspnet
<reply@reply.github.com>
wrote:
Thanks for the contribution and the discussion here. Let me clarify things a
bit.

Here is how I view the yo aspnet project and goals. yo aspnet should be the primary method for users to get started with ASP.NET 5 on any
platform. When users use yo aspnet they can be sure that they are getting high quality templates which align with the templates delivered from Visual Studio.

By align I do not mean that they are exactly the same content. There are situations
where the output of yo aspnet can be different than what VS produces. We already have a few differences. For
example yo aspnet uses the EF in memory store for DB because we don't have a persistence story
for DB on xplat.

I think we should use yo aspnet as an avenue to channel specific feedback on templates to the ASP.NET team.
Whenever a contribution comes in that meets the following.

 * Is high quality
 * The community agrees that it's a positive addition

Then we should take the contribution. At that point I'll work with the ASP.NET
team to try and get the next version of the VS templates updated. Ideally we can
keep the templates in sync for the most part to keep updates simple. If for some
reason VS is not able to make the changes then for areas that we diverge we'll
have to be aware so that we don't lose those on the next asp.net release when
templates are updated.

For this particular PR it sounds like we are hearing good feedback from the
community here, and I know that @markrendle [https://github.com/markrendle] is an ASP.NET expert so I'm sure it's also high quality. @markrendle [https://github.com/markrendle] I noticed that the build is failing, could you update the PR to get the tests
to pass? I think you just need to delete one or more test cases. Does anyone
have any concerns with the PR?

I didn't realize that Visual Studio references a 2 year old bootstrap package.
I've brought this up with Scott Hunter and we should certainly get that fixed in
the VS templates.

—
Reply to this email directly or view it on GitHub
[https://github.com/OmniSharp/generator-aspnet/pull/268#issuecomment-120479082] .[https://github.com/notifications/beacon/AAK4Ql3VSdD57-SSpz3dpmp-560OaYheks5ob_-IgaJpZM4FVSk_.gif]

**Comment by juliosueiras** [comment]
Hi, sorry to bother, but this might be useful for Visual Studio Online users who is using this generator,

(don't know if this is a bug or something easy fix in VSO)
since when using build definition(using only dnx dnu and gulp+bower combination , so not using msbuild) 

for some reason VSO will take bower invalid-meta as a error(which is warning not error, and this happens in jquery-validation, and jquery-validation-unobtrusive) but using gulp-bower won't have that issues

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Do you have any news on this? I've seen couple of different implementation for this problem (I'm using gulp-main-bower-files streamlined solution for this exact problem myself).
The code by @markrendle in this PR can be a little too wide and not feature-specific, but the idea behind PR needs some solution.
Thanks!

**Comment by spboyer** [comment]
Can we move this to an issue? I like the discussion that is here and want to have more input on it. 

@markrendle @peterblazejewicz @sayedihashimi

**Comment by peterblazejewicz** [comment]
As the PR is stalled, the topic moved to issue:
https://github.com/OmniSharp/generator-aspnet/issues/400

> Can we move this to an issue? I like the discussion that is here and want to have more input on it.

**Pull request closed without merging**
