### PR TITLE
Pass variables to templates

### PR DESCRIPTION
**Pull request by saper**

### CODE REVIEW

**Comment by sayedihashimi** [comment]
If I understand the changes correctly, this is an imprint improved way to pass the parameters to the templates.

Looks good to me. @spboyer any concerns?

**Comment by spboyer** [comment]
Looks good to me :shipit:

**Comment by peterblazejewicz** [comment]
@saper 
Please write down commit message and force update - there should be no commit without a message, or we get lost

**Comment by saper** [comment]
There is a one-line comment, is more info needed?

**Comment by sayedihashimi** [comment]
I think he was suggesting adding something in the description field. I went ahead and merged it.

**Comment by sayedihashimi** [comment]
@peterblazejewicz is there problems with commits that have a title but no description? If so could you elaborate on them?

**Comment by saper** [comment]
I like elaborate commit messages, but this change is trivial. I have no experience with yeoman but there seems to be lot if redundancy in the code. I almost didn't notice that `bower.js` needs `applicationname `, for example.

**Comment by spboyer** [comment]
@saper yes there is some room for cleanup here no doubt. Function was the first focus.

**Comment by saper** [comment]
Fine. One example how the redundancy could be reduced a bit is in pull request #94.

**Comment by peterblazejewicz** [comment]
>  is there problems with commits that have a title but no description? If so could you elaborate on them?

Yes, the commit message describes exactly what the 3rd argument is for in `template` Yeoman's action - not for what this commit is for (as in your previous guess):
http://yeoman.github.io/generator/actions.html
> Object Hash to pass to the template. Leave undefined to use the generator instance context.

The commit is very sparse in the words compared to documentation I think, just my opinion though.

**Pull request merged**
