### PR TITLE
Fix merge conflict in README

### PR DESCRIPTION
**Pull request by matteofigus**
/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@matteofigus Thanks!
We have this already covered:
https://github.com/OmniSharp/generator-aspnet/pull/637
Some RC2 commits went into master.

@sayedihashimi 
Maybe just merge RC2 into master right now without publishing yet to NPM?. This will solve this and other possible problems. We will have to add a banner to README that current master is already unstable though.

**Comment by matteofigus** [comment]
Ok. Should I close this so?

**Comment by sayedihashimi** [comment]
>Maybe just merge RC2 into master right now without publishing yet to NPM?. This will solve this and other possible problems

Sounds good

**Comment by matteofigus** [comment]
Thanks, looking forward to the fix. Great work btw!

**Comment by peterblazejewicz** [comment]
@matteofigus Thanks!

**Pull request closed without merging**
