### PR TITLE
:arrow_up: Update Web Application for beta8. Closes #385

### LINKED ISSUE #385: ASP.NET Beta8: WebApp template (Auth)
Samples: http://1drv.ms/1PSX6FB

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- remove hosting.ini
- remove config.json
- add appsettings.json
- great beta8 renaming
- implementation changes
- update copy routine
- update test coverage

Thanks!

```
dnx web
info    : [Microsoft.Framework.DependencyInjection.DataProtectionServices] User profile is available. Using '/Users/piotrblazejewicz/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@peterblazejewicz can you add `web.config`? See my comments at https://github.com/OmniSharp/generator-aspnet/pull/394#issuecomment-147052236

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
OK

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
added `web.config`, rebased and tested on local OS

**Comment by sayedihashimi** [comment]
Thanks merged it

**Pull request merged**
