### PR TITLE
adding editor files, fix whitespace and fs functions from merge

### PR DESCRIPTION
**Pull request by spboyer**

### CODE REVIEW

**Comment by spboyer** [comment]
* Closes https://github.com/OmniSharp/generator-aspnet/issues/113
* Fixes some minor issues from previous merge conflict for fs functions

**Comment by spboyer** [comment]
@peterblazejewicz give this a look for approval

**Comment by sayedihashimi** [comment]
@madskristensen could you review the .editorconfig file?

**Comment by spboyer** [comment]
Open to any suggestions or changes, these were based on the files linked in #113

**Comment by madskristensen** [comment]
@sayedihashimi Looks good to me

**Pull request merged**
