### PR TITLE
Update WebBasic for RC1.  Closes #466.

### LINKED ISSUE #466: ASP.NET 5 RC1 Web Application Basic - No Auth template
Samples:
http://1drv.ms/1QiuMQs

Feed:
https://www.myget.org/F/aspnetrc1

### PR DESCRIPTION
**Pull request by Spinarooni**

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
everything OK,
except of this problem:
https://github.com/OmniSharp/generator-aspnet/issues/466#issuecomment-156226901
I've got 500 on os x.

**Comment by peterblazejewicz** [comment]
@Spinarooni 
You need to update PR to include a fix:
https://github.com/OmniSharp/generator-aspnet/issues/466#issuecomment-156296467
(and squash into single commit please if possible)
After change the `blocking` label can be removed

**Comment by Spinarooni** [comment]
@peterblazejewicz PR updated.

**Comment by peterblazejewicz** [comment]
@Spinarooni Thanks! 
LGTM
@sayedihashimi ?

**Comment by spboyer** [comment]
:+1:

**Comment by peterblazejewicz** [comment]
Thx Sayed & Shayne!

**Pull request merged**
