### PR TITLE
Removed .remote(), added mocha test coverage for all application types etc.

### PR DESCRIPTION
**Pull request by spboyer**
Removed .remote(), 
added mocha test coverage for all application types and sub generators. 
Added scripts section to package.json for Travis CI support.

You can run test by executing `npm test` be sure to first do `npm install` to restore any dependencies and `npm link` to run locally.

@sayedihashimi 
@peterblazejewicz

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@spboyer 
I've got all tests passing locally:
```bash
[...]
      ✓ mvcTest/Views/Shared/_Layout.cshtml created. 


  49 passing (502ms)
```
Will let you know about created content asap.

**Comment by peterblazejewicz** [comment]
@spboyer I won't be able to verify if content is runnable on OS X - but that is rather @aspnet/Home problem.

**Comment by sayedihashimi** [comment]
Sorry for the delay I'm just getting to this. I will try it out and report back. I noticed that the Travis CI build failed with the [error below](https://travis-ci.org/OmniSharp/generator-aspnet/builds/49651367).

```
1) aspnet - Empty Application "before all" hook:

Uncaught TypeError: First argument needs to be a number, array or string.

at new Buffer (buffer.js:188:15)

at EditionInterface.module.exports [as read] (/home/travis/build/OmniSharp/generator-aspnet/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:9:36)

at template (/home/travis/build/OmniSharp/generator-aspnet/node_modules/yeoman-generator/lib/actions/actions.js:191:34)

at yeoman.generators.Base.extend.writing (/home/travis/build/OmniSharp/generator-aspnet/app/index.js:103:18)

at /home/travis/build/OmniSharp/generator-aspnet/node_modules/yeoman-generator/lib/base.js:408:16

at processImmediate [as _immediateCallback] (timers.js:354:15)

npm ERR! Test failed. See above for more details.

npm ERR! not ok code 0

The command "npm test" exited with 1.
```

**Comment by sayedihashimi** [comment]
The changes are really amazing, thanks a lot for putting this together. Now the new project experience is really fast and works on an airplane :) People are really gonna like this improvement.

OK the test cases were passing locally and I tried out the changes and things look to work so I merged it. Let's see if it passes from the master branch.

@spboyer @peterblazejewicz Should we go ahead and release it?

**Comment by sayedihashimi** [comment]
FYI I have updated the instructions on [how to release](https://github.com/OmniSharp/generator-aspnet/wiki/How-to-Publish-Changes), let me know if you guys have questions on that.

**Comment by spboyer** [comment]
@sayedihashimi great! Forgot about these pages.

**Comment by peterblazejewicz** [comment]
@sayedihashimi I can't say here nothing conclusively - I still cannot compile some of project templates due to some changes in kvm/kre as in linked topic:
https://github.com/aspnet/Home/issues/310
I can compile a projects that are in aspnet/home `dev` branch but some of ours fail to compile at the moment on my machine.

**Comment by sayedihashimi** [comment]
@peterblazejewicz when I got latest I did ```kvm upgrade``` and ran through ```kpm restore``` and ```kpm build``` for all projects and they all worked except the unit test and this was because ```xUnit``` was not found. That will get fixed later when ```xUnit``` goes to ```nuget.org```.

I haven't tried any updates from aspnet ```dev```.

What version of mono do you have? I have ```3.8.0```.

**Comment by spboyer** [comment]
@peterblazejewicz @sayedihashimi I bui all projects on OSX Yosemite with mono 3.8.0, and on Windows 8.1 in VS 2015 CTP 5. 

Only challenge I have is Travis CI is failing but local test are passing. Need to see why, npm locally is 2.8.x, need to look at how to make sure Travis is running the same. I'm a noob there.

**Comment by sayedihashimi** [comment]
When I updated kvm threw homebrew now things are hosed. @spboyer you may want to keep the setup you currently have until it's resolved.

Previously I was using mono ```3.8.0``` and after ```brew upgrade kvm``` and then ```kvm upgrade``` mono was updated to ```3.12.0``` and kvm was upgraded as well. I switched mono back to ```3.8.0``` with ```brew switch mono 3.8.0``` from my previous install. After that ```kpm restore``` was still failing so I think its with the ```kvm``` brew formula or something. Not sure. I'll reply back to the issue on aspnet.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
```
mono --version
Mono JIT compiler version 3.10.0 (tarball Wed Oct 22 10:06:03 BST 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```
```
k --version
1.0.0-beta3-11030
```

**Comment by sayedihashimi** [comment]
OK I spent some time on this and got things working here is what I found.

When I was running ```kvm upgrade``` it was pulling the latest ```beta3``` packages from ```myget.org```. I spent some time trying to figure out where ```myget.org``` was coming from but was unable to figure that out. Instead what I did was set the ```KRE_FEED``` env var to nuget.org and then reinstalled kvm. Here are the commands I used.

```
export KRE_FEED="https://www.nuget.org/api/v2"
rm -r -f ~/.kpm/packages/
kvm install 1.0.0-beta2 -p
```

I deleted the ```~/.kpm/packages/``` to remove any packages which may have come from myget or other branches. It's safe to delete that folder. It will come back when ```kpm restore``` is invoked.

Using ```-p``` updates ```default.alias``` to point to the ```beta2``` runtime, and it will remain that until you run ```kvm install -p``` or ```kvm upgrade```.

After that run ```yo aspnet``` to create a new project, and then ```kpm restore``` and ```kpm build```.

@peterblazejewicz can you try it out and let me know if it works for you?

It might make sense to export KRE_FEED="https://www.nuget.org/api/v2" to the profile script so that you're using nuget.org by default.

**Comment by peterblazejewicz** [comment]
@sayedihashimi busy testing

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Every example except of NancyApplication restore, builds and runs with the above solution.
Unfortunately the Nancy project fails to build, here is an output from terminal:
https://gist.github.com/peterblazejewicz/5909c2d36e64930170e6

Thanks for sticking with this problem

**Comment by sayedihashimi** [comment]
@peterblazejewicz how about the other project types? Are they working for you? We have Nancy updates in a commit which has not been published so I'm hoping that may fix it but have not yet tested.

**Comment by peterblazejewicz** [comment]
@sayedihashimi Sayed, yes, every other sample project restores, builds and runs just fine with above.
:dancer:

**Comment by sayedihashimi** [comment]
@peterblazejewicz ok, that's fine for now. We can revisit Nancy after beta3 is on ```nuget.org```.

**Comment by peterblazejewicz** [comment]
SGTM :+1:

**Pull request merged**
