### PR TITLE
[UPD] Nancy project.json dependencies updated to latest versions

### PR DESCRIPTION
**Pull request by jpinho**
Hi there, I've been playing around with yo aspnet generators and I notice that the samples dependencies were outdated. I took the time to fixed it for us, hope it helps.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@jpinho Thanks! still no dice: https://gist.github.com/peterblazejewicz/a01bf6bb92a51cb1b1a7 (I've used to have no problems with vNext on my machine :( )
@sayedihashimi @spboyer you guys decide (and push some folks with this recent *nix problems, it starts to be PITA)

**Comment by jpinho** [comment]
@peterblazejewicz The aim of this commit is essentiality about upgrading Nancy's version, so can you try to revert your OWIN dependency to:

```
"Microsoft.AspNet.Owin": "1.0.0-alpha4"
```

Give it a try. If it works I suggest we procede with this debug on a different pull request, so the community can start using Nancy 1.0 ASAP :) .

**Comment by peterblazejewicz** [comment]
@jpinho no difference -  personally I'll advice to merge this - as @sayedihashimi already merged other PR even if we have problems with building it locally (again, mostly me).
:+1:

**Comment by jpinho** [comment]
@peterblazejewicz Ok thanks, sorry to hear that :( .

**Comment by spboyer** [comment]
@peterblazejewicz @jpinho can you just update the Nancy items? Want to make sure that we do not have build issues with the samples.

**Comment by jpinho** [comment]
@spboyer done, it's passing. I restored OWIN and Kestrel to their initial versions, leaving just nancy dependency with the most up to date version 1.0.0.

**Comment by spboyer** [comment]
Merged. Thanks for the update.

**Pull request merged**
