### PR TITLE
change string from ASP.NET 5 to ASP.NET Core

### PR DESCRIPTION
**Pull request by horsdal**
Not tied to any issue.

Summary of the changes in this PR:
 - Changed texts from using the ASP.NET 5 name to use the ASP.NET Core
 - Changed text in README
 - Changed texts used in `yo` interface
 - Changed texts in generated UI

/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by spboyer** [comment]
Is this a duplicate of #557 ?

**Comment by horsdal** [comment]
Mostly yes, sorry about that.
I seem to have 4 more files in my commit, though.

Let me rebase and see how close we are.

**Comment by horsdal** [comment]
Yes, for the most part duplicate. I also changed generated UIs to use ASP.NET Core and MVC Core instead of ASP.NET 5 and MVC 6.

**Comment by peterblazejewicz** [comment]
@horsdal 
I think the content and names should be the same as in [aspnet/Templates](https://github.com/aspnet/Templates). For example, a different  `Core 1` name:
https://github.com/aspnet/Templates/blob/eeac2d81410a60cab9a4fd006da7a50627cbac3d/src/BaseTemplates/StarterWeb/Project_Readme.html#L136
and so on.
Thanks!

**Comment by peterblazejewicz** [comment]
@horsdal 
https://github.com/peterblazejewicz/missing-aspnet-readme
It's build via script. You can copy&paste into PR
Thanks!

**Comment by sayedihashimi** [comment]
We have removed the "1". So its "ASP.NET Core", the changes here look good. See https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Project_Readme.html

**Comment by horsdal** [comment]
I'm in luck then :wink:

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
There are still some minor differences (`ASP.NET Core MVC` <> `ASP MVC Core`)

**Pull request merged**
