### PR TITLE
Update Web API Template for beta8. Closes #383

### LINKED ISSUE #383: ASP.NET Beta8: Web API Template
Samples: http://1drv.ms/1PSX6FB

### PR DESCRIPTION
**Pull request by spboyer**
This PR updates the Web API Template addresses #383

* adds new wwwroot/web.config file
* removes hosting.ini
* minor changes to Startup.cs
* tests updates
* project.json changes for exclusions on publish

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@spboyer 
Maybe without `web.config`? it's VS artefact AFAIK

**Comment by spboyer** [comment]
@peterblazejewicz sure I can remove the web.config, wasn't *positive* on that. First I'd seen it.

**Comment by peterblazejewicz** [comment]
In the `beta8` annoucement @DamianEdwards mentions that `web.config` will be now definitely gone:
https://github.com/aspnet/Announcements/issues/69#issue-107048558
though I assume the tooling still generate it with VS for broader support with IIS, etc.
Again we should ask in doubt. Previously we haven't included `web.config`s

**Comment by spboyer** [comment]
removing for now.

**Comment by sayedihashimi** [comment]
When using the `web` command `web.config` shouldn't be needed. It's only needed for IIS/IIS Express. Now that I think of it we should likely add that because the app may not work on the remote machine w/o that file when hosted in IIS.

Since we are not sure I think we should add `web.config` back to be on the safe side.

**Comment by peterblazejewicz** [comment]
@sayedihashimi OK

**Comment by peterblazejewicz** [comment]
ping 
@spboyer

**Comment by spboyer** [comment]
@peterblazejewicz added back, CI passed, merge when ready

**Comment by peterblazejewicz** [comment]
:+1: 
Works on my OS
@sayedihashimi :shipit:

**Comment by sayedihashimi** [comment]
Thanks merged it

**Pull request merged**
