### PR TITLE
Update Readme to reflect generator-aspnet-xtianus

### PR DESCRIPTION
**Pull request by xtianus79**
This is the addition and linkage to generator-aspnet-xtianus

### CODE REVIEW

**Comment by spboyer** [comment]
@xtianus79 thanks for updating. Would you make one edit here 

Asp.net -> ASP.NET

Thanks.

**Comment by xtianus79** [comment]
sure thing

**Comment by sayedihashimi** [comment]
Also can you expand "VS" to "Visual Studio".

After that I think we are ready to merge this.

**Comment by xtianus79** [comment]
sure thing

**Comment by sayedihashimi** [comment]
@xtianus79 thanks, merged it. Can you also send a PR to edit https://github.com/OmniSharp/OmniSharp.github.io/blob/master/index.md#yeoman-generators?

**Pull request merged**
