### PR TITLE
Changed the Web, MVC and Nancy templates to point to the beta3 bits

### PR DESCRIPTION
**Pull request by larsw**
of the ASP.NET 5 stack. Nancy is now pointing at 1.1.0 (latest as of now).

### CODE REVIEW

**Comment by larsw** [comment]
After further testing, the Web and MVC templates works - more work has to be done to fix the Nancy template.

**Comment by larsw** [comment]
Ok to pull now; Web, MVC & Nancy generated projects build successfully.

**Comment by nosami** [comment]
Looks good to me

**Comment by sayedihashimi** [comment]
Adding @spboyer who was looking at this as well

**Comment by larsw** [comment]
Hmm, something is fishy here - it seems like that I managed to merge in some View Component stuff into the wrong branch in my repo or something (since it refers to larsw/MvcViewComponent a bit up here.)

**Comment by larsw** [comment]
Ok, think I manage to revert the commit.

**Comment by spboyer** [comment]
The standard templates will be changing with [this issue](https://github.com/OmniSharp/generator-aspnet/issues/70), let's hold off on making changes to the current samples.

**Comment by spboyer** [comment]
Updating Nancy, xUnit - :+1:

**Comment by larsw** [comment]
ah, ok.

**Comment by jchannon** [comment]
We should try to sync this with the changes done by @spboyer, maybe continue this branch with those additional changes

**Comment by sayedihashimi** [comment]
@larsw @jchannon @spboyer see my comments at https://github.com/OmniSharp/generator-aspnet/pull/73#issuecomment-76331639.

**Pull request closed without merging**
