### PR TITLE
Updated Readme with link to F# Templates Source

### PR DESCRIPTION
**Pull request by odytrice**
Updated Readme
Thanks!

/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Should I make a new release?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Sayed, Yes, please. I'll make some correction to README in upcoming hours, but they are not exactly most important right now. Up to you. The code works on *Nix, I assume it should work on Dotnet Core platform x-platform.

**Comment by sayedihashimi** [comment]
publish started https://travis-ci.org/OmniSharp/generator-aspnet/builds/164283926

@odytrice thanks a lot for the F# contributions, this is really great.

**Comment by odytrice** [comment]
It's an honor to be of service to the community :smile:

**Pull request merged**
