### PR TITLE
Update Web Application template for beta6. Closes #276

### LINKED ISSUE #276: ASP.NET 5 beta6  WebApp with authentication template
Sample is uploaded http://1drv.ms/1LAz7uJ

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR updates Web Application template for beta6
The differences in code were detected and validated using FileMerge tool on Mac OS X.

That PR is a WIP PR, as at the moment that resulting application once created with generator simply does not restore completely due to EntityFramework missing on nuget:
```
OK https://nuget.org/api/v2/FindPackagesById()?id='System.IO' 2613ms
Unable to locate EntityFramework7.InMemory >= 7.0.0-beta6
Unable to locate EntityFramework7.Commands >= 7.0.0-beta6
Writing lock file /Users/piotrblazejewicz/dev/WebApplication/project.lock.json
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks' 3030ms
Restore complete, 4290ms elapsed
Errors in /Users/piotrblazejewicz/dev/WebApplication/project.json
    Unable to locate EntityFramework7.InMemory >= 7.0.0-beta6
    Unable to locate EntityFramework7.Commands >= 7.0.0-beta6
```

I've created nuget.config as described for beta and restored using beta feed:
```
dnu restore -f https://nuget.org/api/v2/
```

```
   / _ \/ |/ / | / /  |/  /
  / // /    /| |/ / /|_/ / 
 /____/_/|_/ |___/_/  /_/  

.NET Version Manager - Version 1.0.0-beta6-10396
```

Otherwise update passes Mocha tests

@sayedihashimi

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
It does not restore or build. Is that OK to merge it?

**Comment by sayedihashimi** [comment]
@peterblazejewicz EntityFramework dropped the `7` in the name of the package. I've changed it in the `project.json` in https://github.com/OmniSharp/generator-aspnet/commit/ff7f51856455f0e5c1f334a14d2e78b19babcd76 and merged your changes.

**Comment by sayedihashimi** [comment]
@peterblazejewicz I fixed it. See the comment I just posted.

**Comment by peterblazejewicz** [comment]
@sayedihashimi Oh, that's OK.
Thanks!

**Comment by peterblazejewicz** [comment]
I've just verified with updated beta6 generator that Web App project correctly restore/builds and run under OS X and updated EF references.
Thanks!

**Pull request merged**
