### PR TITLE
:arrow_up: Update Nancy template for RTM. Closes #775 [WIP]

### LINKED ISSUE #775: Update Nancy Template after RTM
The Nancy template project are behind the other projects.
It should be at least updated for RTM

/cc @jchannon

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is WIP  - do not merge if not ready. This does not work out-of-the-box using information for RTM:
https://github.com/OmniSharp/generator-aspnet/issues/760

To test this PR locally (after installing update dotnet runtime):
```
- yo aspnet
- cd NancyApplication
- yo aspnet:nuget --unstable
- dotnet restore --no-cache
- dotnet run
```

The original sample baking this project update is available on Nancy reppo:
https://github.com/NancyFx/Nancy/tree/master/samples/Nancy.Demo.Hosting.Kestrel

The project fails to restore dependencies correctly. I could have miss correct packages and deps.
The main blocker can be correct configuration in `project.json`:
https://github.com/peterblazejewicz/generator-aspnet/blob/5a6b663eef9939909c59ad72794ebb36db6e0651/templates/projects/nancy/project.json

/cc
@OmniSharp/generator-aspnet-team-push
@jchannon 

This commit updates Nancy project template for RTM.
Changes:
- project structure is updated for Dotnet core application
structure with Program.cs and Startup.cs
- the content of example is updated and based on Nancy sample:
Nancy.Demo.Hosting.Kestrel: https://git.io/voHvc
- tests have been updated to cover additional content
- tests have been updated to no use Nancy project in other
features tests as after this update the Nancy projet will have
similar structure to ASP.NET Core web projects

Thanks!

### CODE REVIEW

**Comment by jchannon** [comment]
I'm not sure using the Nancy Kestrel demo as a template is a good idea. I think a template should be clean as possible.

This won't compile as you are using newer routing syntax in Nancy that is not in the package 1.4.3.

We are trying to get our build script moved to Cake from Rake and then we can get a nuget package out.  If anyone wants to help in that effort it would be gratefully received, its taking much longer than expected 😢

**Comment by peterblazejewicz** [comment]
@jchannon 

> I'm not sure using the Nancy Kestrel demo as a template is a good idea. I think a template should be clean as possible.

Honestly, I'm newcomer to C# (and Windows OS) and current Nancy template shows nothing to me compared even to Empty Web project, even ASP.NET *Hello*  web project is much more featured:
https://github.com/aspnet/Home/tree/dev/samples/1.0.0-rc1-update1/HelloWeb. But read below

> This won't compile as you are using newer routing syntax in Nancy that is not in the package 1.4.3.
We are trying to get our build script moved to Cake from Rake and then we can get a nuget package out. If anyone wants to help in that effort it would be gratefully received, its taking much longer than expected

Understandable.
Let's make deal: when you're ready with Nancy we will split Nancy project into Nancy 'Hello World' (taken literally from project web site) and this one or with similar features set, which can help to better present project interoperability with ASP.NET Core to get better traction for newcomers.
[I've read your ticket on aspnet/Templates about Nancy](https://github.com/aspnet/Templates/issues/517)
I've started using xUnit @ work thanks to this and similar projects btw.
Thanks!

/cc
@sayedihashimi

**Comment by peterblazejewicz** [comment]
removed RTM label as it will be after RTM

**Comment by peterblazejewicz** [comment]
As explained - scheduled for after RTM update. Depends on Nancy project upgrades
Thanks!

**Pull request closed without merging**
