### PR TITLE
add gitignore file

### PR DESCRIPTION
**Pull request by spboyer**
closes https://github.com/OmniSharp/generator-aspnet/issues/98

uses template from -> https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

### CODE REVIEW

**Comment by xtianus79** [comment]
this is probably a sill question but where is this file when running a project? As of now when you run the generator a gitignore file is not created correct?  I held off from putting in my own because it seems there is a lot more to ignore which this file seems to robustly do.  I guess I was just missing it.  for example when you create a project in Visual studio the above gitignore is added but not seen?

**Comment by peterblazejewicz** [comment]
@spboyer  Could you consider resubmitting with white space changes stashed in `app/index.js`? There are some white space related changes that bump this PR up in size. The commit without changes in white space:
https://github.com/OmniSharp/generator-aspnet/pull/112/files?w=1
This could help in case of rebasing other PRs.

**Comment by peterblazejewicz** [comment]
@xtianus79 
The PR code copies `.gitignore` into project root (resolved via target path + application name.). The current state of Git + `.gitignore` in VS2013 can be read here I believe: https://msdn.microsoft.com/en-us/library/hh967655.aspx#ignore. I don't know what are upcoming features in VS.

**Comment by spboyer** [comment]
@peterblazejewicz not sure how to re-submit without the whitespace. is it a huge deal on this PR?

**Comment by peterblazejewicz** [comment]
@spboyer No, I'll face it. I'd merge your PR first, then rebase #108 and only after this continue with #108

**Pull request merged**
