### PR TITLE
Update Web Application Basic project template for beta6.  Closes #277.

### LINKED ISSUE #277: ASP.NET 5 beta6 WebApp No Auth project
Sample is uploaded http://1drv.ms/1LAz7uJ

### PR DESCRIPTION
**Pull request by Spinarooni**

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
That's wrong. What has been actually changed? It seems that beta6 ships without Grunt support - which is not reflected in the PR:
https://github.com/OmniSharp/generator-aspnet/issues/286

**Comment by peterblazejewicz** [comment]
We are free to go. Sayed checked and Grunt templates are simply not changed (and they generated Gulp version, which is default).
Thanks and sorry for the hassle

**Comment by sayedihashimi** [comment]
I haven't tried it yet, I will tomorrow. One thing I noticed is that we have `1.0.0-*` for the dependencies. @Spinarooni can you change `*` to `beta6`?

**Comment by Spinarooni** [comment]
@sayedihashimi I'll update the PR.

**Comment by Spinarooni** [comment]
PR updated.

**Comment by sayedihashimi** [comment]
Thanks @Spinarooni, I've merged it to beta6

**Pull request closed without merging**
