### PR TITLE
Add web root directory to web sample

### LINKED ISSUE #1: Update index.js to pull from this repo
Currently [index.js](https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js) is pulling from the old LigerShark repo using `.remote()`. We should update that to pull source files from this repo instead.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR adds empty web root directory for Web type sample used by generator. The web root directory is specified in project file (also modified) and follows MVC sample.
This closes #1 of:
https://github.com/OmniSharp/generator-aspnet/issues/31

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@sayedihashimi 

> I also noticed that there was an empty .gitignore file in wwwroot was that on purpose?

I've added `.gitignore` after scanning project how empty directories are added - personally I would use `.gitkeep` empty file by convention instead of `.gitignore` in project.

> Do you think we should add a readme.md or readme.html in wwwroot folder in the empty template stating that static assets will go in wwwroot? Users may not know otherwise why its there.

I know that `*.html` use for documentation is VisualStudio artefact - probably because it can render html natively within window panel now. But I think most projects either use Markdown - which is readable without any rendering support or plain TXT files. The '*.html' is simply an unreadable content without rendering support - but I know that the VS still creates `.html` files as project documentation files - maybe it will change in future.

The additional bonus of using Markdown content is that on Github it is rendered by default to html markup and easier to read.

Again, it's up to project leaders which format should be used in documentation. I'll opt for markdown personally.

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks so let's add a ```readme.md``` into ```wwwroot```. Since we will have a file there and not an empty directory we should be able to avoid ```.gitignore``` and ```.gitkeep```.'

Thanks.

**Comment by peterblazejewicz** [comment]
The PR is updated to reflect @sayedihashimi  comment. The draft version of readme follows article from ASP.NET, quoting the most informative section for user and providing a link to entire post:

---

> All of the static files in your project go into this folder. These are assets that the app will serve directly to clients, including HTML files, CSS files, image files, and JavaScript files. The `wwwroot` folder is the root of your web site. That is, `http://hostname/` points to `wwwroot`, all URLs for static content are relative to the `wwwroot` folder.

We have taken the quote above on the role of the `wwwroot` directory, the static files and assets in the vNext projects, from this excellent article on ASP.NET (which you should read for all the details):

[http://www.asp.net/vnext/overview/aspnet-vnext/grunt-and-bower-in-visual-studio-2015#static-files](http://www.asp.net/vnext/overview/aspnet-vnext/grunt-and-bower-in-visual-studio-2015#static-files)

**Comment by sayedihashimi** [comment]
Thanks merged

**Pull request merged**
