### PR TITLE
:arrow_up: Update xUnit template for RTM

### PR DESCRIPTION
**Pull request by peterblazejewicz**
/cc
@OmniSharp/generator-aspnet-team-push

This commit updates xUnit template for RTM

- project.json has been restructured to follow
xUnit documentation: https://git.io/vo9hv
- the link to xUnit documentation has been updated
to dotnet version:
- the xunit.runner.json configuration file has been
added to provide fully fledged template for users
consisting of project folder, sample test and configuration
for test runners. The configuration contains example keys
with default values

/cc @bradwilson

Thanks!

```
yo aspnet

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |  marvellous ASP.NET Core |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of application do you want to create? Unit test project (xUnit.net)
? What's the name of your ASP.NET application? UnitTest
   create UnitTest/.gitignore
   create UnitTest/project.json
   create UnitTest/SampleTest.cs
   create UnitTest/xunit.runner.json


Your project is now created, you can use the following commands to get going
    cd "UnitTest"
    dotnet restore
    dotnet build (optional, build will also happen when it's run)
    dotnet test


➜  development cd UnitTest 
➜  UnitTest yo aspnet:nuget --unstable
You called the aspnet subgenerator with the arg _nuget.config
NuGet.config created.
   create NuGet.config
➜  UnitTest dotnet restore --no-cache
log  : Restoring packages for /Users/piotrblazejewicz/development/UnitTest/project.json...
log  : Writing lock file to disk. Path: /Users/piotrblazejewicz/development/UnitTest/project.lock.json
log  : /Users/piotrblazejewicz/development/UnitTest/project.json
log  : Restore completed in 2922ms.
➜  UnitTest dotnet test
Project UnitTest (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling UnitTest for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.6470495
 

xUnit.net .NET CLI test runner (64-bit .NET Core osx.10.11-x64)
  Discovering: UnitTest
  Discovered:  UnitTest
  Starting:    UnitTest
    UnitTest.SampleTest.FailingTest [FAIL]
      Assert.Equal() Failure
      Expected: 5
      Actual:   4
      Stack Trace:
        /Users/piotrblazejewicz/development/UnitTest/SampleTest.cs(22,0): at UnitTest.SampleTest.FailingTest()
  Finished:    UnitTest
=== TEST EXECUTION SUMMARY ===
   UnitTest  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 0.251s
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
➜  UnitTest
```

### CODE REVIEW

**Comment by bradwilson** [comment]
FYI, those instructions are based on Preview 1, and will undoubtedly change for Preview 2.

**Comment by peterblazejewicz** [comment]
@bradwilson Can you add me to /cc when updating xUnit docs? thanks!

**Comment by bradwilson** [comment]
Will do. My hope is that the Preview 2 packages will allow me to get rid of the imports statements. ;)

**Comment by bradwilson** [comment]
The docs have been updated: https://xunit.github.io/docs/getting-started-dotnet-core.html

/cc @peterblazejewicz

**Pull request merged**
