### PR TITLE
Update the mocha and chai deps in package.json

### PR DESCRIPTION
**Pull request by scottaddie**
Updated the mocha and chai npm modules to the latest versions available, as discussed in PR https://github.com/OmniSharp/generator-aspnet/pull/420.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
LGTM Tested locally, Node 4.2.1
:ship:

**Comment by peterblazejewicz** [comment]
```
npm install
vs_projectname@1.0.2 node_modules/vs_projectname

uuid@2.0.1 node_modules/uuid

findup-sync@0.3.0 node_modules/findup-sync
└── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@3.0.0)

chai@1.10.0 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

chalk@1.1.1 node_modules/chalk
├── escape-string-regexp@1.0.3
├── ansi-styles@2.1.0
├── supports-color@2.0.0
├── strip-ansi@3.0.0 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

yosay@1.0.5 node_modules/yosay
├── ansi-regex@1.1.1
├── ansi-styles@2.1.0
├── word-wrap@1.1.0
├── strip-ansi@2.0.1
├── pad-component@0.0.1
├── minimist@1.2.0
├── taketalk@1.0.0 (get-stdin@4.0.1)
├── repeating@1.1.3 (is-finite@1.0.1)
└── string-width@1.0.1 (strip-ansi@3.0.0, is-fullwidth-code-point@1.0.0, code-point-at@1.0.0)

mocha@2.3.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── diff@1.4.0
├── growl@1.8.1
├── supports-color@1.2.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── debug@2.0.0 (ms@0.6.2)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

yeoman-generator@0.19.2 node_modules/yeoman-generator
├── read-chunk@1.0.1
├── detect-conflict@1.0.0
├── diff@1.4.0
├── yeoman-welcome@1.0.1
├── xdg-basedir@1.0.1
├── user-home@1.1.1
├── rimraf@2.4.3
├── async@0.9.2
├── mime@1.3.4
├── text-table@0.2.0
├── dargs@4.0.1 (number-is-nan@1.0.0)
├── shelljs@0.4.0
├── run-async@0.1.0 (once@1.3.2)
├── yeoman-assert@1.0.0 (lodash@2.4.2, chalk@0.5.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@3.0.0)
├── findup-sync@0.2.1 (glob@4.3.5)
├── underscore.string@3.2.2
├── class-extend@0.1.2 (object-assign@2.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── nopt@3.0.4 (abbrev@1.0.7)
├── cross-spawn@0.2.9 (lru-cache@2.7.0)
├── cli-table@0.3.1 (colors@1.0.3)
├── mem-fs-editor@1.2.3 (vinyl@0.4.6)
├── lodash@3.10.1
├── sinon@1.17.1 (formatio@1.1.1, samsam@1.1.2, lolex@1.3.2, util@0.10.3)
├── gruntfile-editor@1.0.0 (ast-query@1.0.1)
├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
├── yeoman-environment@1.2.7 (escape-string-regexp@1.0.3, log-symbols@1.0.2, untildify@2.1.0, grouped-queue@0.3.0, globby@2.1.0, mem-fs@1.1.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── html-wiring@1.2.0 (detect-newline@1.0.3, cheerio@0.19.0)
├── github-username@1.1.1 (get-stdin@1.0.0, got@2.9.2)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.4.2)
├── dateformat@1.0.11 (get-stdin@5.0.0, meow@3.4.2)
├── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.4.0, cli-width@1.1.0, through@2.3.8, readline2@0.1.1, rx@2.5.3)
└── download@4.4.0 (gulp-rename@1.2.2, object-assign@4.0.1, is-url@1.2.1, vinyl@1.0.0, read-all-stream@3.0.1, stream-combiner2@1.1.1, filenamify@1.2.0, readable-stream@2.0.2, concat-stream@1.5.1, each-async@1.1.1, vinyl-fs@2.2.1, got@5.0.0, ware@1.3.0, caw@1.1.0, gulp-decompress@1.1.0)
```

**Comment by peterblazejewicz** [comment]
@scottaddie 
btw: thanks for splitting topics

**Comment by scottaddie** [comment]
@peterblazejewicz No problem. I should've known to do that.

**Pull request merged**
