### PR TITLE
Update documentation and usage file

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is documentation cleanup, so the project can be ready for beta8 and RC1 releases

- reword vNext to ASP.NET 5 (phase out vNext usage)
- do not use fenced code backticks for single line words (Github flavour)
- sort USAGE list of subgenerators
- sort list of subgenerators in main README
- move sections according to sorted subgenerator list
- add missing Unit test project to list

So basically:
- items are sorted in lists
- sections are moved according to sorted list positions

As  large parts of README content were moved you could get wrong impression what changed using only diff view. One should get better overview of changes when using 'Split' view in some cases.

Thanks!

### CODE REVIEW

**Comment by spboyer** [comment]
LGTM

**Comment by Spinarooni** [comment]
Looks good.

**Comment by peterblazejewicz** [comment]
@sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks merged it

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Thanks! Now, mind looking into #378?

**Pull request merged**
