### PR TITLE
Update WebAPI project template for beta5. Closes #189

### LINKED ISSUE #189: ASP.NET Web API Template for Beta5
https://onedrive.live.com/redir?resid=43459A6389A804D9!94676&authkey=!AK_F4dzipIag-U8&ithint=file%2czip

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit updates WebAPI project template to one coming with beta5:
- new hosting.ini file added to project
- updated project.json
- new README.md based on current html README document from ASP.NET
- the ValuesController renamed and moved into more proper directory structure
- updated copy syntax to use fs-mem module
- the tests are updated to new content and updated structure

This commit also updates WebAPI controller subgenerator as directly related to
WebAPI project and using the same content

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
previous PR:
https://github.com/OmniSharp/generator-aspnet/pull/199

**Comment by sayedihashimi** [comment]
@peterblazejewicz looks like there was a build failure related to ```Startup.cs```

**Comment by peterblazejewicz** [comment]
The commit is updated with @rustd comments and rebased and squashed with current beta5.

It does restore OK now, but fails on build and run:
https://gist.github.com/peterblazejewicz/899c5b595792a739e264
https://gist.github.com/peterblazejewicz/41015b681d27817d6543
https://gist.github.com/peterblazejewicz/ef70a7ebce5e965e6efc

I can see a lot of beta4 bits mixed with beta5 in this setups.

**Comment by peterblazejewicz** [comment]
The Travis is failing on tests that pass locally:
```
  aspnet - Web API Application
    Checking directories
      ✓ Application directory created
      ✓ Controllers directory created
      ✓ Properties directory created
      ✓ wwwroot directory created
    Checking files
      ✓ webAPITest/Controllers/ValuesController.cs created.
      ✓ webAPITest/hosting.ini created.
      ✓ webAPITest/project.json created.
      ✓ webAPITest/Properties/launchSettings.json created.
      ✓ webAPITest/Startup.cs created.
      ✓ webAPITest/wwwroot/README.md created.
```

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz I've merged it. I think the test was failing because of a casing issue, see https://github.com/OmniSharp/generator-aspnet/commit/e6681f236f1156e1a4336c5b9421cc28b87205a3.

I was able to build and run w/o errors. If you are still having errors try the following:
 - delete packages folder in ```~/.dnx/packages```
 - set dnvm to beta5
 - restore packages with ```dnu restore -f https://nuget.org/api/v2```
 - build and run

**Pull request merged**
