### PR TITLE
Added info for cd-ing into right directory after application creation

### PR DESCRIPTION
**Pull request by marcusoftnet**
It's just a very small thing, but the rest of the tool is so helpful, I was missing this. 

Admitting that I couldn't test this... Can someone fill me in on how to run this locally? 
Also, felt a bit weird to test the output of a helpmessage, but happy to do with some pointer

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@marcusoftnet Marcus, integration tests are hard for console-based tools. The Yeoman provides built-in features to test and mock files/directories creation and content of files so they are used in project tests:
https://github.com/yeoman/yeoman-assert/blob/master/index.js
Thanks for addition!
LGTM :shipit:

**Comment by peterblazejewicz** [comment]
FYI, the output with this PR looks like:
```
Your project is now created, you can use the following commands to get going
    cd ConsoleApplication
    dnu restore
    dnu build (optional, build will also happen when it's run)
    dnx . run for console projects
    dnx . kestrel or dnx . web for web projects
```

**Comment by marcusoftnet** [comment]
Thanks for that @peterblazejewicz for that input. 

The output you gave was what I intended so I'm happy with that too.

**Comment by marcusoftnet** [comment]
Oh well... looks good to me provided that the name you gave your application was: ```ConsoleApplication```.

**Comment by nosami** [comment]
The directory name needs to be escaped in case it includes spaces etc.

**Comment by peterblazejewicz** [comment]
@nosami 
Good catch. Can just use double quotes? I think double quotes will work both in Windows and *nix terminals.

**Comment by marcusoftnet** [comment]
Oh, good point. Added that now

**Pull request merged**
