### PR TITLE
Fix race condition with grunt bower-install task.  Fixes issue #254.

### PR DESCRIPTION
**Pull request by Spinarooni**

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
LGTM
```
➜  WebApplication  grunt
Running "bower:install" (bower) task
>> Installed bower packages

Done, without errors.
```
```
➜  WebApplicationSimple  grunt
Running "bower:install" (bower) task
>> Installed bower packages

Done, without errors.
```
@spinarooni Do you get the same output?

**Comment by Spinarooni** [comment]
Yes, I did.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'll marge this. Can you up-vote/ this change to be introduced/discussed via core VS template team? The problem could slip under the radar during updates.

**Comment by sayedihashimi** [comment]
@peterblazejewicz I have created https://github.com/aspnet/Tooling/issues/107 so that the VS templates get updated as well.

**Pull request merged**
