### PR TITLE
:arrow_up: Update Empty Application for beta8. Closes #382

### LINKED ISSUE #382: ASP.NET Beta8: Empty WebApp Template
Samples: http://1drv.ms/1PSX6FB

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- remove hosting.ini from project
- rewrite kestrel/web commands
- update copy routine
- update test

Thanks!
```
dnx web
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

### CODE REVIEW

**Comment by spboyer** [comment]
:+1:

**Comment by sayedihashimi** [comment]
@peterblazejewicz can you add `web.config`? See my comments at https://github.com/OmniSharp/generator-aspnet/pull/394#issuecomment-147052236

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
rebased, updated and tested on local OS

**Comment by sayedihashimi** [comment]
Thanks merged it

**Pull request merged**
