### PR TITLE
Add description for --grunt option in help.  Closes #244.

### LINKED ISSUE #244: Provide correct descriptions for default options for better 'usage' via '--help'
The underlying Yo generator base outputs default options descriptions when using 'yo aspnet --help':
https://github.com/yeoman/generator/blob/master/lib/base.js#L240-L276
``` 
Usage:
  yo aspnet:app [options] 

Options:
  -h,   --help        # Print the generator's options and usage
        --skip-cache  # Do not remember prompt answers           Default: false
        --grunt       # Description for grunt

Description:
```
The better description for options is required, most notable point is `grunt` option here - people can read this from README.md, but should be able to do via command line, as Yo is console tool.

thanks!

### PR DESCRIPTION
**Pull request by Spinarooni**
Output should now be:

    λ yo aspnet --help
    Usage:
      yo aspnet:app [options]
    
    Options:
      -h,   --help# Print the generator's options and usage
    --skip-cache  # Do not remember prompt answers  Default: false
    --grunt   # Generates a Gruntfile.js file for web templates instead of gulp.js

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Spinarooni thanx,
The text should talk about `Grunt`, not `Gruntfile.js` and also mentions default options being false, so if you don't mind, can you consider updating to something like:
```
this.option('grunt', {
      type: Boolean,
      desc: 'Use Grunt during build process instead of Gulp',
      defaults: false
    });
```
The copy text of `desc` is something up to you, here is how official docs uses Gulp/Grunt:
http://docs.asp.net/en/latest/client-side/grunt-gulp.html

Thanks!

**Comment by Spinarooni** [comment]
Is this better:

    yo aspnet:app [options]
    
    Options:
      -h,   --help# Print the generator's options and usage
    --skip-cache  # Do not remember prompt answers Default: false
    --grunt   # Use the Grunt JavaScript task runner instead of Gulp in web projects.  Default: false

**Comment by peterblazejewicz** [comment]
For me LGTM. Please update PR
/cc for text copy proofing
@sayedihashimi

**Comment by Spinarooni** [comment]
@peterblazejewicz  Updated the PR.

**Comment by peterblazejewicz** [comment]
Thanks!

**Comment by sayedihashimi** [comment]
Thanks guys

**Pull request merged**
