### PR TITLE
Add package restore for Bower and NPM in web projects.  Closes #294 a…

### LINKED ISSUE #294: lib folder missing
In the asp.net 5, there are three environments (1) Development (2) Staging and (3) Production. Using the command **set ASPNET_ENV = Development** at the command line, the project can be run with development settings. In the development environment, the **_Layout.cshtml*** refers a **lib** folder

``` html
        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="~/winstrap/css/winstrap.css"/>
        </environment>
```

During the scaffolding, the **lib** folders are not deployed which should contain the css and js files. Please see the attached image.

yo

### PR DESCRIPTION
**Pull request by Spinarooni**
…nd #295.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Thanks!
I have some objections though: the install is supposed to be a part of .NET application bootstraping I think. 
When someone invokes `dnu restore` the client side dependencies could also be installed. That is why Sayed has cc/-ed folks from MS to get input on this problem on the other topic.
If we use approach from PR people will 99% wait until client side deps get installed - even if scaffolded project is never restored and build/run.
It's not that I'm against this PR, but simply the topic of correctly bootstraping ASP5 web application is not yet established I think. Usually when scaffolding a web application via generators the dependencies are installed as last step, so PR is correct, but here only client-side dependencies are installed, not ones from NuGet.

cc
@sayedihashimi

**Comment by Spinarooni** [comment]
@peterblazejewicz You could spawn a command for `dnu restore` as well using yeoman.

	this.spawnCommand('dnu', ['restore']);

**Comment by peterblazejewicz** [comment]
> Understanding ASP.NET 5 Web Apps*_
http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html?highlight=postrestore
[...]
The default ASP.NET project template has scripts in place to run during postrestore and prepare that install client side dependencies using npm and bower.

Running or spawning a command from Yo has no relation how bootstrapping project is evangelized in ASP.NET documentation. We know we could run `npm` or `bower` in many different ways, to problem is to implement that feature in envisioned way.

**Comment by Spinarooni** [comment]
Ok, no problem.

**Comment by sayedihashimi** [comment]
We used to call restore automatically after create, people complained about it. They wanted to change dep then restore when they are ready.

**Comment by Spinarooni** [comment]
@sayedihashimi I'm not sure if this would make a difference but this change employs a `--skip-install` flag that bypasses the automatic package restore if the user wants to.

**Comment by sayedihashimi** [comment]
Based on previous feedback I think not installing should be the default.

**Comment by peterblazejewicz** [comment]
Folks writing docs are nearly there in how MS seems to implement this in its sources:
> For example, the following is scaffolded when creating a new application in Visual Studio:
```
{
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }
}
```
http://docs.asp.net/en/latest/dnx/projects.html?#scripts
So there is a progress on that subject.
I'm using `postrestore` and `postbuild` right now, until MS provides unified way on how to handle dependencies across tooling

**Comment by peterblazejewicz** [comment]
@Spinarooni 
Thanks! Appreciated

**Pull request closed without merging**
