### PR TITLE
fix for guid token on connection string

### PR DESCRIPTION
**Pull request by spboyer**
Closes issue# https://github.com/OmniSharp/generator-aspnet/issues/102

### CODE REVIEW

**Comment by spboyer** [comment]
@peterblazejewicz can you review this so we can get this merged?

**Comment by peterblazejewicz** [comment]
@spboyer 
We need `.editorconfig` file :D See our PR without taking white space into consideration:
https://github.com/OmniSharp/generator-aspnet/pull/110/files?w=1
https://github.com/OmniSharp/generator-aspnet/issues/113

I'd change the PR here: the `guid` is deprecated module:
```
generator-aspnet git:(pr/110) npm link
npm WARN deprecated guid@0.0.12: Please use node-uuid instead. It is much better.
```
https://github.com/broofa/node-uuid
Thanks!

**Comment by spboyer** [comment]
@peterblazejewicz changed to uuid, good suggestion there.  If it looks good to you I'll merge.

**Comment by peterblazejewicz** [comment]
So I've got:
```
"Server=(localdb)\\mssqllocaldb;Database=aspnet5-WebApplication-ecc5fec5-1c72-4647-8749-8fb7fa871b46;Trusted_Connection=True;MultipleActiveResultSets=true"
```
when running updated PR.

LGTM
:shipit:

**Pull request merged**
