### PR TITLE
updating gitignore template to match latest from github

### PR DESCRIPTION
**Pull request by sayedihashimi**
Updated the content of gitignore.txt template to match the latest in https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore

@peterblazejewicz can you review?

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
- we use Bower and have correct reference in our file
Our `.gitignore` should look more like this:
https://github.com/yeoman/generator-angular/blob/master/templates/common/root/gitignore
- but we could add that web-centred entires later - so `bower_components` are here to stay.

**Comment by sayedihashimi** [comment]
@peterblazejewicz are you saying that ```bower_components``` should remain in ```.gitignore```? If so I think we should have a discussion at https://github.com/aspnet/Tooling. The content was taken from the default ```.gitingore``` for Visual Studio.

**Comment by spboyer** [comment]
Yes `bower_components` should remain, this folder should not be a part of a commit to a repo. As you would also exclude node_modules and nuget resources.

When a Dev pulls the code, the should get the dependencies based on the package.json, bower.json files using  restore cmd or `npm install` and `bower install`

**Comment by sayedihashimi** [comment]
@peterblazejewicz @spboyer OK I've added ```bower_components``` back to the ```,gitignore``` template here. I will discuss with @madskristensen and @DamianEdwards regarding the default content for Visual Studio. They are leaning towards not ignoring it so that the content can be checked in for users who would like that flow.

**Comment by sayedihashimi** [comment]
I've merged it.

**Pull request merged**
