### PR TITLE
Add missing closing for x-ua-compatible tag in websimple template.

### PR DESCRIPTION
**Pull request by Spinarooni**
Also fix production bootstrap css file fallback path in same template.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Spinarooni Thanks!

LGTM

**Comment by sayedihashimi** [comment]
According to this [accepted StackOverflow answer](http://stackoverflow.com/a/26348511/105999) there is no benefit to adding this and there may be drawbacks.

Adding @rustd and @DamianEdwards to let us know whether this should be added for sure. Thougths?

**Comment by DamianEdwards** [comment]
Yeah it isn't needed in a template. Apps that really need it can it add if they think they have reason to.

**Comment by sayedihashimi** [comment]
Ok closing based on @DamianEdwards comment.

@Spinarooni could you open a new pr for bootstrap fallback?

**Comment by peterblazejewicz** [comment]
I've added `ie-edge` tag, as we started following H5BP project recomendations (based on their discussion):
https://github.com/OmniSharp/generator-aspnet/commit/07b3d29795604d059fad0bedabcf114ee5aaf629
I do think that tag is helpful, especially in organisations that use modern .NET applications with legacy one and sometimes force settings in browsers (like mine company), that's to early to remove this and this tag I think.
Otherwise we should follow simple barebone template with just HTML5 doctype (as on JSBin.com)
Thanks!

**Pull request closed without merging**
