### PR TITLE
Update Config subgenerator to be an AppSettings subgenerator. Closes …

### PR DESCRIPTION
**Pull request by Spinarooni**
…#426.

Thoughts?

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I still don't know. Can we just add new subgenerator and left `config.json` as is until rc-1?

**Comment by Spinarooni** [comment]
@peterblazejewicz Seems ok to me to add the new generator.

**Comment by sayedihashimi** [comment]
LGTM

**Comment by peterblazejewicz** [comment]
:shipit:

**Pull request merged**
