### PR TITLE
:arrow_up: Update/yeoman generator 0.20.0

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR updates dependency `yeoman-generator` to version 0.20.0.
As there were breaking changes with this update to  copyTpl/copy implementation
and tests were failing that is required that someone validates this PR on different machine.

To correctly validate this PR make sure that your local dependencies are updated:
```
rm -rf node_modules
npm install
```
Then run `npm test`

Thanks!

Thanks!
/cc @OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by jackjwilliams** [comment]
On Windows 10, I receive the following (unrelated to your changes) error:

 ```
1) aspnet:UserSecrets It creates expected keys in project.json "before all" hook:
     Uncaught Error: Error parsing your configuration file: [./project.json]: Unexpected end of input
      at File.loadSync (C:\projects\generator-aspnet\node_modules\nconf\lib\nconf\stores\file.js:160:11)
      at Provider.add (C:\projects\generator-aspnet\node_modules\nconf\lib\nconf\provider.js:137:23)
      at Provider.file (C:\projects\generator-aspnet\node_modules\nconf\lib\nconf\provider.js:63:15)
      at RunContext.<anonymous> (C:\projects\generator-aspnet\test\usersecrets.js:154:21)
      at RunContext.<anonymous> (C:\projects\generator-aspnet\node_modules\yeoman-generator\lib\test\run-context.js:98:10)
      at Generator.<anonymous> (C:\projects\generator-aspnet\node_modules\yeoman-generator\lib\base.js:398:10)
      at Queue.<anonymous> (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:68:12)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:79:43)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at SubQueue.run (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\subqueue.js:42:45)
      at Queue.next (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:80:39)
      at Queue._exec (C:\projects\generator-aspnet\node_modules\grouped-queue\lib\queue.js:83:3)
      at Generator.<anonymous> (C:\projects\generator-aspnet\node_modules\yeoman-generator\lib\base.js:484:7)
      at C:\projects\generator-aspnet\node_modules\async\lib\async.js:726:13
      at C:\projects\generator-aspnet\node_modules\async\lib\async.js:52:16
      at iterate (C:\projects\generator-aspnet\node_modules\async\lib\async.js:260:24)
      at async.forEachOfSeries.async.eachOfSeries (C:\projects\generator-aspnet\node_modules\async\lib\async.js:281:9)
      at _parallel (C:\projects\generator-aspnet\node_modules\async\lib\async.js:717:9)
      at Object.async.series (C:\projects\generator-aspnet\node_modules\async\lib\async.js:739:9)
      at Conflicter.resolve (C:\projects\generator-aspnet\node_modules\yeoman-generator\lib\util\conflicter.js:86:9)
      at Generator.<anonymous> (C:\projects\generator-aspnet\node_modules\yeoman-generator\lib\base.js:479:21)

```

**Comment by jackjwilliams** [comment]
I might have had some conflicting packages, a clean checkout followed by a fetch of this PR with npm install tested just fine.

**Comment by peterblazejewicz** [comment]
> I might have had some conflicting packages, a clean checkout followed by a fetch of this PR with npm install tested just fine.

Yes, that's plausible explanation. All that PRs with version bumps require clearing local deps before testing.

**Comment by peterblazejewicz** [comment]
@jackjwilliams Thanks!

**Comment by jackjwilliams** [comment]
@peterblazejewicz No problem, unfortunately the error is back though. Rather strange, subsequent runs after that first passing run fail with the same error. Not sure if its just my system (most likely). I've added some console.logs:


```
aspnet:UserSecrets
    It does not create any file artefacts when called in directory without project.json
      √ there is no project.json created in current directory
    It does not override existing keys in project.json
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with ./project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\73308a55c598b2796fba8ea2af5d0406a5509104\webTest
Debug: File = ./project.json
Debug: Attempting to parse
Debug: End - Parse Successful ------------------------------
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with C:\Users\Josh\AppData\Local\Temp\73308a55c598b2796fba8ea2af5d0406a5509104\webTest\project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\73308a55c598b2796fba8ea2af5d0406a5509104\webTest
Debug: File = C:\Users\Josh\AppData\Local\Temp\73308a55c598b2796fba8ea2af5d0406a5509104\webTest\project.json
Debug: Attempting to parse
Debug: End - Parse Successful ------------------------------
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with ./project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\73308a55c598b2796fba8ea2af5d0406a5509104\webTest
Debug: File = ./project.json
Debug: Attempting to parse
Debug: End - Parse Successful ------------------------------
      √ There is a project.json file already created
      √ The userSecretId key is not overriden
      √ the UserSecrets nuget package version is not changed
    It creates expected keys in project.json
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with ./project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\16f25df73a708f9e30deca6dfb6554bdf6a3f61e\emptyTest
Debug: File = ./project.json
Debug: Attempting to parse
Debug: End - Parse Successful ------------------------------
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with C:\Users\Josh\AppData\Local\Temp\16f25df73a708f9e30deca6dfb6554bdf6a3f61e\emptyTest\project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\16f25df73a708f9e30deca6dfb6554bdf6a3f61e\emptyTest
Debug: File = C:\Users\Josh\AppData\Local\Temp\16f25df73a708f9e30deca6dfb6554bdf6a3f61e\emptyTest\project.json
Debug: Attempting to parse
Debug: End - Parse Successful ------------------------------
Debug: Start ---------------------------------
Debug: nconf\stores\file.js loadSync with ./project.json
Debug: Context
Debug: Directory = C:\Users\Josh\AppData\Local\Temp\16f25df73a708f9e30deca6dfb6554bdf6a3f61e\emptyTest
Debug: File = ./project.json
Debug: Attempting to parse
[SyntaxError: Unexpected end of input]
```

**Comment by peterblazejewicz** [comment]
@jackjwilliams 
That's related to this updated. I've tested at work. It needs to be investigated. When runnin from current master there is no problem, only if updated dependencies are used from this PR/branch.
Thanks!

**Comment by jackjwilliams** [comment]
In trying to understand whats happening, I see that here in test\usersecrets.js:

helpers.run(require.resolve('../UserSecrets'))
            .inDir(targetDir)
            .on('end', function() {
              // reset project reprentation
              nconf.remove('file');
              nconf.file({ /// LINE THAT FAILS
                file: './project.json'
              });
              done();
            });

We are running ../UserSecrets/index.js, which also calls this._getProject()

var project = nConf.file({
    file: this._projectPath
  });

My understanding of yeoman and its class hierarchy is limited though, this was just some initial digging. I'm not even sure I understand what the purpose of that block of code in test\usersecrets is doing. It says reset project representation. There could be some race condition where the ./project.json file is locked or not available.

**Comment by peterblazejewicz** [comment]
@jackjwilliams 
It has to run via Yo's helpers to:
1) scaffold an project template with or without project.json file and store originally created data into vars
2) run a subgenerator on scaffolded project to apply changes
hence two different async Yo's helper methods.
I've added `path.resolve(...)` and added breakpoints (via VSCode) and have not yet determined the problem.
When run in isolation 'mocha test/usersecrets.js` it does not fail now on Windows. But fails when part of suite.

**Comment by peterblazejewicz** [comment]
This should be investigated after RC2 release. For now closing

**Pull request closed without merging**
