### PR TITLE
Less redundancy in the writing code

### PR DESCRIPTION
**Pull request by saper**
Use auxiliary functions
`tpl()`, `cpy()`, `dir()` to
reduce amount of duplication
in the 'writing' code.

Converted almost automatically with
the following `sed` script:

    s/this.copy(/cpy(/
    s/this.template(/tpl(/
    s/this.directory(/dir(/
    s/this.sourceRoot() + //
    s/this.applicationName + //
    s/, *this.templatedata);/);/

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Wait! Why overwrite Yeoman built-in action just to get what exactly? 
http://yeoman.github.io/generator/actions.html

**Comment by saper** [comment]
Good catch, but unfortunately I don't see `bulkTemplate` there, which would have been most helpful...

**Comment by peterblazejewicz** [comment]
No, people who wrote this code were just using very verbose and literal syntax. This @spboyer commit:
https://github.com/saper/generator-aspnet/commit/53d0ee7bffe246328c761b3b4a3f8427e2744152
could use documented Yeoman features - assumption that `source` and `destination` roots are either default to application or are set before copy/template operation. This code could be simply refactored to use default source/desitionations directories or just set them. Link again:
http://yeoman.github.io/generator/actions.html
Just like the other guys do:
https://github.com/yeoman/generator-angular/blob/master/app/index.js#L307-L311
Don't get me wrong, but adding all this stuff will just hide a code that requires refactoring (shortening) - which is always welcome I think.

**Comment by saper** [comment]
It seems that changing `this.destinationRoot(this.applicationName)` breaks npm tests...

**Comment by peterblazejewicz** [comment]
This PR removes completely option to modify data object passed to template on per-file basis. Am I correct with this? What if template needs a little one field more, e.g. common banner fields or we should not pass a data object at all.

**Comment by saper** [comment]
It is trivial to update `tpl` to do this as well. But it was not required as of now (the only variable passed were `namespace` and sometimes `applicationname`). I just wonder if this is a good idea to have the the same variable name set to different values for different files... Can be nightmare for debugging.

My experience from other templating languages suggests that maybe it's better to unnecessary poison variable namespace for templates that don't need all of the variables set as compared to carefully cherry-picking variables for every template. If the need arises, there can be two or more sets of `templatedata`.

I am neither `yeoman/yo` nor ASP expert so I have no idea what will be better here, for me this is just a drive-by project, as @xtianus79 asked me for help with his fork.

Feel free to re-work my ideas/commits as you wish.

**Comment by spboyer** [comment]
The verbosity of the `web` template makes it appears as if there is a lot of redundancy. I agree that there is a need to do some clean up. Just want to make sure it is done in a way that we are not re-doing it again when other templates are added.

**Pull request closed without merging**
