### PR TITLE
Started Work on FSharp Templates

### LINKED ISSUE #785: Support for F# Projects
Is there a hidden way to create a F# project, if not please add F# support soon!

### PR DESCRIPTION
**Pull request by odytrice**
Attempts to Fix #785.

Added F# Folder and Templates for
 - FSharp Empty Web Application
 - FSharp Class Library
 - FSharp Console Application

Not Entirely sure how Yeoman is configured. But I guess this is a start
Thanks!

/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
FYI: I've added `WIP` label because of tests failing

**Comment by odytrice** [comment]
Thanks. But how do I run the tests? Mocha? Jasmine?

**Comment by Spinarooni** [comment]
@odytrice Mocha.  Just run `npm test` from the root of the project if you have all the project dependencies installed (`npm install`).

**Comment by peterblazejewicz** [comment]
@odytrice 
If you are stuck:
- can you start new PR with just one project first? e.g. Let's go with class library first
and second:
- can we follow convention for names from dotnet/cli using: `fsharp_lib`(a lower case - convention used here) instead of nested directories?
https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new

**Comment by odytrice** [comment]
Aiight, Let me do just that

**Pull request closed without merging**
