### PR TITLE
Add simple Web Application template for beta5. Closes #190

### LINKED ISSUE #190: ASP.NET Web App Template with No Auth for Beta5
https://onedrive.live.com/redir?resid=43459A6389A804D9!94677&authkey=!AAC66v3yHucrpvU&ithint=file%2czip

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR adds 'Web Application Simple' option to main application generator to create a web application project template without membership and authorization (but also without services, migrations, etc).
- add new project template content based on web project without
membership and authorization implementation
- add new application generator option for this kind of project
- write new tests to cover new generator option
- update project documentation

The PR includes test coverage for this project. I've managed to `dnu restore` this project without a problem, again I have a problems building this content and running it under `beta5` on my Mac.
So this PR requires actual review on other machine.

Thanks!

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz, I've merged it.

**Comment by peterblazejewicz** [comment]
@sayedihashimi what about naming? Does it cut? The old 'starter web' was nice one.

**Comment by sayedihashimi** [comment]
@peterblazejewicz still waiting to hear from @shanselman regarding this. I went ahead and merged it because we can change the name later on. I think what we have now is pretty clear with the ```[without Membership and Authorization]```, but I like Empty/WebApplication/StarterWeb as well.

**Comment by peterblazejewicz** [comment]
'starter', 'empty' are catchy names. Also 'Hello Web' still exists: http://git.io/vtKwK

**Pull request merged**
