### PR TITLE
Add link to Readme for Visual Studio template extension

### PR DESCRIPTION
**Pull request by GregTrevellick**
Fixes bug number: N/A

Summary of the changes in this PR:
 - Added link to visual studio marketplace project template extension https://marketplace.visualstudio.com/items?itemName=GregTrevellick.OmniSharpAspNetVsix

Thanks!

/cc
@OmniSharp/generator-aspnet-team-push

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Hi Greg,
This project is in dormant state from some time as its primary objectives were - I believe, met with `dotnet cli` tool based ecosystem:
https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x
I really appreciate your work on the extension, but I'm not sure if that PR will be merged now.
Thanks!

**Comment by GregTrevellick** [comment]
No worries Peter - I've another Yeoman template extension I'll be publishing soon anyway, and I learnt a lot building the Omnisharp one anyway. Cheers :-)

**Comment by peterblazejewicz** [comment]
Cool! Cheers Greg!

**Comment by sayedihashimi** [comment]
Thanks for the PR, the work here is now been replaced with `dotnet new`.

**Pull request closed without merging**
