### PR TITLE
Update WebApplication template for beta7. Closes #317

### LINKED ISSUE #317: ASP.NET Web App (With Auth) for beta7
Feed used: https://www.myget.org/F/aspnetliterelease/api/v2 
Samples are here: https://onedrive.live.com/redir?resid=43459A6389A804D9%21102054

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR updates WebApplication template project for beta7:
- update project structure
- add new content (Models/ViewModels/etc)
- rename content
- remove files
- add new tests
- update existing tests
- update Razor templates
- update dnx usage hints

As reported in #316 updated project does not restore (so does not build and run too) due to missing package(s):
```
Restore complete, 37309ms elapsed

Errors in /Users/piotrblazejewicz/development/WebApplication/project.json
    Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7
    Unable to locate Microsoft.Dnx.Compilation.CSharp >= 1.0.0-beta7

NuGet Config files used:
    /Users/piotrblazejewicz/.config/NuGet/NuGet.Config
    /Users/piotrblazejewicz/development/WebApplication/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetbeta7/api/v2/
    https://nuget.org/api/v2/

Installed:
    42 package(s) to /Users/piotrblazejewicz/.dnx/packages
```

The changes in project structure forced updates to Mocha tests. All new files are covered by tests. The tests are updated to reflect removed or renamed content.

All files are ported/updated *as is* - with a single exception for `_ValidationScriptsPartial.cshmtl` - from which protocols in srcs are not moved to project - as '_Layout' scripts also do not have protocol in srcs:
```cshtml
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/jquery.validate.js"
            asp-fallback-test="window.jquery && window.jquery.validator">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jquery && window.jquery.validator && window.jquery.validator.unobtrusive">
    </script>
</environment>
```

Thanks!

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
The `project.json` has been updated to use `beta7` as per @rustd comments. Still, the project does not restore correctly:
```
Errors in /Users/piotrblazejewicz/development/WebApplication/project.json
    Unable to locate Microsoft.Dnx.Compilation.CSharp >= 1.0.0-beta7
    Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7
```

**Comment by rustd** [comment]
Please use the following feed which has these packages http://myget.org/gallery/aspnetbeta7take2

**Comment by peterblazejewicz** [comment]
The errors are different when using *take2* feed:
```
dnu restore -f https://nuget.org/api/v2/                
Microsoft .NET Development Utility Mono-x64-1.0.0-beta7-15524

Restoring packages for /Users/piotrblazejewicz/development/WebApplication/project.json
  CACHE https://www.myget.org/F/aspnetbeta7take2/
  CACHE https://nuget.org/api/v2/
  CACHE https://www.myget.org/F/aspnetbeta7take2/FindPackagesById()?id='Microsoft.Dnx.Compilation.CSharp'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='Microsoft.Dnx.Compilation.CSharp'
  CACHE https://www.myget.org/F/aspnetbeta7take2/FindPackagesById()?id='System.Reflection'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
  CACHE https://www.myget.org/F/aspnetbeta7take2/FindPackagesById()?id='System.Threading.ThreadPool'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Threading.ThreadPool'
  CACHE https://www.myget.org/F/aspnetbeta7take2/FindPackagesById()?id='System.Net.Sockets'
  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Net.Sockets'
Unable to locate Microsoft.Dnx.Compilation.CSharp >= 1.0.0-beta7
Writing lock file /Users/piotrblazejewicz/development/WebApplication/project.lock.json
Restore complete, 4105ms elapsed

Errors in /Users/piotrblazejewicz/development/WebApplication/project.json
    Unable to locate Microsoft.Dnx.Compilation.CSharp >= 1.0.0-beta7

NuGet Config files used:
    /Users/piotrblazejewicz/.config/NuGet/NuGet.Config
    /Users/piotrblazejewicz/development/WebApplication/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetbeta7take2/
    https://nuget.org/api/v2/
```
The `Microsoft.Dnx.Compilation.CSharp.Common` is now listed in feed but not: `Microsoft.Dnx.Compilation.CSharp`:
http://myget.org/gallery/aspnetbeta7take2

**Comment by rustd** [comment]
It is uploaded to the feed. Please try again

**Comment by sayedihashimi** [comment]
When I run it I'm getting the following error, I'm not sure if this is a machine issue though. I'm still investigating.

```
ayeds-MacBook-Pro:WebApplicationBasic sayedhashimi$ dnx kestrel
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IApplicationEnvironment] (IServiceProvider provider) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0
  at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0
  at Microsoft.Dnx.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0
  at Microsoft.Dnx.Host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env, System.Runtime.Versioning.FrameworkName targetFramework) [0x00000] in <filename unknown>:0
Sayeds-MacBook-Pro:WebApplicationBasic sayedhashimi$
```

**Comment by peterblazejewicz** [comment]
I now get different package failure:
```
Writing lock file /Users/piotrblazejewicz/development/WebApplication/project.lock.json
Restore complete, 184930ms elapsed

Errors in /Users/piotrblazejewicz/development/WebApplication/project.json
    Unable to locate Microsoft.Dnx.Compilation >= 1.0.0-beta7
```
I've been clearing `~/.dnx/packages` to be sure about that failure.

**Comment by peterblazejewicz** [comment]
rebased/updated

**Comment by sayedihashimi** [comment]
@peterblazejewicz is this working for you now?

**Comment by sayedihashimi** [comment]
@shirhatti can you try this on your machine?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'll try with that different feed right now:
https://github.com/OmniSharp/generator-aspnet/pull/322#issuecomment-136425163

**Comment by peterblazejewicz** [comment]
rebased/up-to-date

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
still no dice:
`Unable to locate Microsoft.Dnx.Compilation >= 1.0.0-beta7`
I cannot see that package on the list: http://myget.org/gallery/aspnetbeta7take2

**Comment by danroth27** [comment]
@muratg Please add Microsoft.Dnx.Compilation to the list of packages to publish and to the take2 feed.

**Comment by danroth27** [comment]
Should be fixed now. Try again.

**Comment by peterblazejewicz** [comment]
@danroth27 
Daniel, that was it! Thanks!
```
dnu restore -f https://nuget.org/api/v2/
Microsoft .NET Development Utility Mono-x64-1.0.0-beta7-15524

Restoring packages for /Users/piotrblazejewicz/development/WebApplication/project.json
  .....
Writing lock file /Users/piotrblazejewicz/development/WebApplication/project.lock.json
Restore complete, 4107ms elapsed

NuGet Config files used:
    /Users/piotrblazejewicz/.config/NuGet/NuGet.Config
    /Users/piotrblazejewicz/development/WebApplication/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetbeta7take2/
    https://nuget.org/api/v2/
```
```
dnu build
Microsoft .NET Development Utility Mono-x64-1.0.0-beta7-15524

......

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.5836850
Total build time elapsed: 00:00:03.6214829
Total projects built: 1
```
```
dnx kestrel
info    : [Microsoft.Framework.DependencyInjection.DataProtectionServices] User profile is available. Using '/Users/piotrblazejewicz/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Application started. Press Ctrl+C to shut down.
```

/cc 
@sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks, merged it

**Comment by sayedihashimi** [comment]
Thanks merged it

**Pull request merged**
